runtime/simple-io.reds
=> FIX: removed redundant print-line in simple-io.reds

environment/actions.red, runtime/actions.reds, runtime/datatypes/block.reds, runtime/datatypes/object.reds, runtime/datatypes/string.reds, runtime/sort.reds, tests/source/units/series-test.red
FIX: wrong result when compare two objects.
TESTS: added test for stable sorting.
=> FEAT: added support for stable sorting.

environment/actions.red, environment/functions.red, runtime/datatypes/none.reds
FEAT: added TAKE action for none! datatype.
=> FIX: issue #1056 (EMPTY? should accept #[NONE] as its parameter)

red.r
Making this fix according to @earl's prososal. Thanks @earl .
=> FIX: Timezone's issue when release a new Red binary.

environment/routines.red
=> change arc* to a*

compiler.r, environment/actions.red, environment/datatypes.red, environment/functions.red, environment/natives.red, environment/operators.red, environment/routines.red, environment/scalars.red, environment/system.red, runtime/case-folding.reds, runtime/datatypes/common.reds, runtime/datatypes/float.reds, runtime/datatypes/string.reds, runtime/datatypes/symbol.reds, runtime/datatypes/vector.reds, runtime/hashtable.reds, runtime/red.reds
Added support for make spec as in R3.
>> make vector! [integer! 16 4 [1 2 3 4]]
Added support for char! and float! on vector!
Added math op! and bitwise op! support for vector! (only char! and
integer!)
Added CLEAR,COPY,POKE,REMOVE,REVERSE,TAKE,SORT actions.
=> FEAT: add more actions for vector! datatype.

runtime/datatypes/string.reds, runtime/datatypes/vector.reds
Note: Only support char! and integer! element now.
=> FEAT: added FIND and SELECT actions for vector! datatype

runtime/datatypes/string.reds, runtime/datatypes/vector.reds
FEAT: added more error checking for vector! datatype
=> FIX: append on vector! does not correctly.

compiler.r, environment/lexer.red, environment/scalars.red, runtime/allocator.reds, runtime/datatypes/block.reds, runtime/datatypes/context.reds, runtime/datatypes/tuple.reds, runtime/hashtable.reds, runtime/macros.reds, runtime/redbin.reds, utils/redbin.r
FEAT: expanded tuple max size to 12 (interpreter only)
=> FIX: Not encoding tuple correctly in redbin

environment/actions.red, runtime/datatypes/map.reds, runtime/hashtable.reds, runtime/interpreter.reds
FIX: throw an error when no set value in set-path!
=> FEAT: MOLD map! handling indentations and /FLAT refinement

boot.red, environment/actions.red, environment/functions.red, runtime/datatypes/vector.reds
FEAT: allowed use arithmetic in float! vector
FIX: fix type-checking for arithmetic actions of vector
=> FEAT: allowed use of a scalar value in vector! arithmetic

environment/system.red, runtime/datatypes/integer.reds, runtime/datatypes/string.reds
#1251 There's probably a better way to phrase the new message.
=> split MAKE/TO error message into two messages

runtime/datatypes/paren.reds
red>> p: first [(1 2 3)]
== (1 2 3)
red>> random p
== (2 1 3)
red>> sort random p
== (1 2 3)
red>> sort/reverse random p
== (3 2 1)
red>>
=> FEAT: sort paren!

compiler.r, environment/lexer.red, environment/natives.red, lexer.r, run-all.r, runtime/datatypes/binary.reds, runtime/datatypes/hash.reds, runtime/datatypes/series.reds, runtime/hashtable.reds, runtime/macros.reds, runtime/natives.reds
FEAT: added support for single-line comments inside binary data
FEAT: added support for base 2 and base 64 binary in compiler
FEAT: added debase native function
=> FEAT: added debase native function

tests/view-test.red
Will look like this: https://files.gitter.im/red/red/xbwB/blob
=> FEAT: enabling image type test using existing image from the repository

modules/view/backends/platform.red, modules/view/backends/windows/gui.reds, modules/view/backends/windows/win32.reds, tests/view-test.red
I wonder if you want it this way or you will just style the field. We will want to change fields flag on runtime anyway, won't we?
=> FEAT: multiline area widget

environment/actions.red, environment/system.red, runtime/actions.reds, runtime/datatypes/binary.reds, runtime/datatypes/file.reds, runtime/datatypes/image.reds, runtime/datatypes/symbol.reds, runtime/simple-io.reds, runtime/unicode.reds
FEAT: throw error when open file failed.
=> FEAT: added support for WRITE action.

environment/functions.red, environment/natives.red, runtime/macros.reds, runtime/natives.reds, runtime/simple-io.reds, system/compiler.r
FIX: literal UTF-16 c-string is not correct in some cases
FEAT: added to-red-file function
=> FEAT: preliminary support for request-file native

modules/view/backends/windows/draw.reds, modules/view/backends/windows/gui.reds, modules/view/backends/windows/win32.reds, modules/view/draw.red, tests/view-test.red
FEAT: temporary enable anti-alias update.
=> FEAT: minimal support for draw TEXT

modules/view/backends/windows/draw.reds
This commit fixes the gdi+ issue on WinXP and also imporves drawing performance.
=> FEAT: using memory dc in Draw.

runtime/platform/POSIX.reds, runtime/platform/darwin.reds, runtime/simple-io.reds
FIX: cannot handle some unsafe url
=> FEAT: URL auto-redirect on Mac OSX

modules/view/backends/windows/gui.reds, modules/view/backends/windows/image.reds, runtime/datatypes/image.reds
FEAT: change image control dynamically
=> FEAT: change group-box's caption dynamically

environment/lexer.red, runtime/datatypes/binary.reds, runtime/natives.reds
FIX: crash when loading float string
=> FIX: cosine doesn't work correctly

modules/view/backends/windows/camera.reds, runtime/datatypes/binary.reds, runtime/datatypes/block.reds, runtime/datatypes/object.reds, runtime/datatypes/string.reds, runtime/datatypes/vector.reds, tests/view-test.red
Conflicts:
runtime/datatypes/object.reds
=> FEAT: compare series/node first when perform compare action on series

modules/view/backends/windows/draw.reds, modules/view/backends/windows/events.reds, modules/view/backends/windows/gui.reds
FEAT: delete draw cache when destory face
=> FIX: avoid draw cached bitmap to many times

modules/view/backends/windows/draw.reds, modules/view/backends/windows/font.reds, modules/view/backends/windows/win32.reds
FIX: temporary fix for avoid crash when not set font style.
=> FEAT: added TEXT support for draw image! datatype

modules/view/backends/windows/text-list.reds, runtime/datatypes/file.reds
=> FEAT: added file! to string! support

modules/view/backends/windows/font.reds, quick-test/call.r, red.r
FIX: issue #1436 (font size too small)
=> FIX: cannot load win-call in some cases

modules/view/backends/windows/draw.reds, modules/view/draw.red, runtime/natives.reds
FIX: do not create brush correctly when color is FFFFFFFFh
=> FIX: issue #1501 ( always iterates over 3 pixels)

modules/view/backends/windows/gui.reds, modules/view/backends/windows/win32.reds, runtime/datatypes/float.reds
Note: This fix is tricky. Maybe not working in some corner cases.
=> FIX: issue #1542 (incorrect conversion from odd whole float! to integer)

tests/align-test.red
@dockimbel Is this close to what you had in mind?
=> Expand align-test.red to test #1576, #1619 & #1488

environment/console/windows.reds, modules/view/backends/windows/events.reds
FIX: the cursor does not show in some cases in gui console.
=> FEAT: filter out window minimize msg in SIZING event(fix #1422)

environment/functions.red
=> FEAT: Allow DIR? to take URL!

README.md, usage.txt
Add notes regarding
-  `--cli` on Windows. (@dockimbel the default mode on other OSes is `cli`, right? )
-  Issue related to Font on Wine https://github.com/red/red/issues/1618
=> Add Some Notes to the Readme

modules/view/backends/windows/draw.reds, modules/view/backends/windows/win32.reds, modules/view/draw.red
FEAT: added pen off support in draw
=> FEAT: added 'radial' and 'diamond' gradient type

environment/lexer.red, lexer.r
This commit fixes the issue when runing this script:
https://github.com/StephaneVeneri/redscripts/blob/master/3d/3dviewer.red
=> FIX: regression on lexer

environment/natives.red, runtime/crypto.reds, runtime/natives.reds, tests/source/units/checksum-test.red
Sorry it's 3 commits instead of 1. Even branched and tried to squash it.
=> New checksum spec and test suite

runtime/crypto.reds
FIX: using allocate memory in get-digest as static array is not thread safe
=> FEAT: new checksum spec for Mac and Linux

modules/view/view.red
=> FIX: #1970 (Too much 'over events on draggable face)

tests/source/units/time-test.red
Lots of stuff commented out that isn't supported yet.
=> New test file for time! values.

environment/functions.red, runtime/datatypes/file.reds, runtime/datatypes/url.reds, runtime/red.reds
FIX: issue #2058 (make-dir/deep returns error)
=> FEAT: create new file path when using path in file

environment/natives.red
=> Removed period from end of checksum doc string.

environment/natives.red, runtime/macros.reds, runtime/natives.reds
Just did a pull --rebase on red/master, so hope this is now in sync.
=> Added native SIGN? function.

environment/console/help.red, environment/functions.red
One line change
Added description for what-dir
In regards to request #2100 
First use of git/github
Advice?
=> updated what-dir

environment/natives.red
I thought this had been done already.
=> Remove period from SIGN? doc string

modules/view/backends/windows/draw.reds, modules/view/backends/windows/win32.reds, modules/view/draw.red, tests/shape-test.red
I have implemented shape dialect for Red with same commands as for R2. Backends: GDI+ and GDI.
I have updated draw arc command for GDI.
=> Shape dialect implementation

modules/view/backends/gtk3/gtk.reds, modules/view/backends/gtk3/gui.reds, modules/view/backends/gtk3/style.reds
- Font support - **NO UPDATE YET**
- `font-size`
- `font-color`
- `style` - (bold, italic, undeline, strike)
- New widgets - **NO UPDATE YET**
- `progress`
- `text`
- `field`
- `area`
- Update view
- `color` for `base`
[Color selection example](http://www.red-lang.org/2016/06/061-reactive-programming.html) working now.
=> Initial font support and new widgets

modules/view/backends/windows/direct2d.reds, modules/view/backends/windows/draw.reds, modules/view/backends/windows/draw.reds.orig, modules/view/backends/windows/events.reds, modules/view/backends/windows/win32.reds, modules/view/draw.red, runtime/definitions.reds, system/runtime/common.reds, tests/complexpen-test.red
Implementation of complex pen as described [here](https://github.com/qtxie/red/wiki/Create-Complex-Pen-in-Draw). Only Windows platform GDI+ backend
=> Complex pen

environment/console/help.red
=> Added object? case statement to help.red

environment/functions.red
=> FIX: REPLACE/ALL works fine with CHAR! PATTERN

README.md
Behold, the unstoppable toddler! :baby_symbol::dash: 
* close missing paren (Galactic Lisp committee demand :alien:);
*  emphasize _Hello World!_ output.
=> FIX: tweak readme slightly

tests/source/units/all-tests.txt, tests/source/units/power-test.red
Hi, I have complete the `power` function unit test
=> power function unit test

tests/source/units/series-test.red
Current output:
```
~~~started test~~~ hash
===group=== hash-put
--test-- hash-put-3 FAILED**************
===group=== hash-select
--test-- hash-select-1 FAILED**************
--test-- hash-select-2 FAILED**************
===group=== hash find
--test-- hash-find-2 FAILED**************
~~~finished test~~~  hash
Number of Tests Performed:      19
Number of Assertions Performed: 31
Number of Assertions Passed:    27
Number of Assertions Failed:    4
****************TEST FAILURES****************
```
=> Add hash! datatype tests

modules/view/view.red
Issue fixed on #3122 but still appears when `system/view/debug?: true`
=> FIX: Functions inside face! objects are called during creation #3131

README.md
Added windows GUI console compilation command.
=> Added windows GUI console compilation command

runtime/datatypes/pair.reds
=> FIX: float values casts to integer during math ops with pairs

environment/console/engine.red
See [Gitter message](https://gitter.im/red/help?at=5ade4b8015c9b0311429ff8f).
=> FIX: word leakage in READ-ARGUMENT

runtime/datatypes/char.reds, tests/source/units/char-test.red
to-char with integer > 10FFFFh and < 0 gives error
=> FIX: Issue #3450

runtime/datatypes/date.reds, tests/source/units/date-test.red
=> FIX: #3469

environment/console/help.red, runtime/natives.reds, tests/source/environment/functions-test.red, tests/source/environment/help-test.red, tests/source/units/evaluation-test.red
Apologies for unrelated commits in the PR.
=> FIX/FEAT: #3487 #3489 help-string and compose

runtime/datatypes/string.reds
=> FIX: TRIM/WITH crashes with BINARY!

environment/functions.red, tests/source/units/replace-test.red
1. Tests added
2. Spaces converted to Tabs
3. Fixed below case (changed `reduce`s to `compose`s)
```
>> replace/case [a b] 'a 'x
*** Script Error: a has no value
```
=> TEST: Added replace/case tests.

environment/functions.red
Also added key support for easy dialog dismissal.
=> FIX: #3586

tests/source/units/all-tests.txt, tests/source/units/draw-test.red
A test file for draw image. Let me know if I'm checking for View availability in a wrong manner.
=> prevent #3607-like regressions

.github/ISSUE_TEMPLATE/bug_report.md
Small fixes here and there: missing spaces, inconsistent capitalization and ellipsis, etc.
=> FIX: minor retouching of issue template

runtime/datatypes/pair.reds, runtime/datatypes/time.reds
This concerns path access in time and pair values.
=> FIX issue #3384 wrong error messages

modules/view/backends/gtk3/gui.reds
text-list, drop-down and drop-list can now be updated when changing data field
=> fix data update

modules/view/backends/gtk3/draw.reds, modules/view/backends/gtk3/events.reds, modules/view/backends/gtk3/font.reds, modules/view/backends/gtk3/gtk.reds, modules/view/backends/gtk3/gui.reds, modules/view/backends/gtk3/handlers.reds, tests/draw.red
I closed the previous PR "Fix scale and image issues on draw".
This PR merges the previous PR updated  with changes that @qtxie asked and the new development on draw fixes.
=> Gtk: patch draw,  scale and resize

environment/functions.red, tests/source/environment/functions-test.red
This PR adds `last?` function.
Test added.
```
>> last? []
== false
>> last? [1]
== true
>> last? make hash! [1]
== true
>> last? make hash! [1 2]
== false
>> last? make vector! [1 2]
== false
>> last? make vector! [1]
== true
>> last? ""
== false
>> last? "1"
== true
```
=> FEAT: Added last? function

environment/reactivity.red
:point_up: [March 4, 2019 11:27 PM](https://gitter.im/red/bugs?at=5c7d8a4c65ffa019ea893de9)
=> 3796 hotfix

runtime/case-folding.reds
Very tiny correction, changed `File: %filename.red` to `File: %case-folding.reds` in `case-folding.reds` file.
=> Added filename.

runtime/platform/win32.reds
Current implementation of `now/precise/time` uses `GetSystemTime` winapi call, which is limited to 1ms. I replace it with 2 calls: `GetSystemTimeAsFileTime` and `FileTimeToSystemTime`. Both are supported by WinXP.
From FileTime I can get not just milliseconds, but 100ns-rounded data. Tests/performance are unaffected.
Since Windows timer is still capped to 1ms period, the time reported by `now/precise/time` will increment by roughly 1ms if called frequently:
```
>> loop 10 [probe now/time/precise loop 3000 ['do 'nothing]]
23:38:40.548467
23:38:40.549467
23:38:40.549467
23:38:40.549467
23:38:40.550467
23:38:40.550467
23:38:40.550467
23:38:40.551467
23:38:40.551467
23:38:40.551467
```
However when called less frequently, the microsecond part changes, showing that the OS timer period is not …
=> High res time query on Windows

environment/functions.red
This PR fixes the compiler incompatible definition of `single?` function.
=> FIX: Fixed issue #3862

environment/console/CLI/win32.reds, modules/view/backends/windows/gui.reds, modules/view/backends/windows/win32.reds
=> FIX: issue #1290 (drop-down and drop-list can crash)

runtime/call.reds
I made a little bit of a mess with the indices in the PR before that only now occurred to me, sorry ☺
=> FIX: patch for commit #8e99d131 (PR #3877)

boot.red, environment/codecs/json.red, environment/codecs/json/common.red, environment/codecs/json/load-json.red, environment/codecs/json/to-json.red, tests/source/units/json-test.red
I'm not entirely sure if I added the tests the right way, please let me know.
=> JSON codec

environment/natives.red, runtime/datatypes/map.reds, runtime/natives.reds, tests/source/units/map-test.red
```
m: #(a 1 b 2 c 3)
foreach [k v] m [print [k v]]
```
Will output: 
```
a 1
b 2
c 3
```
=> Foreach map

modules/view/VID.red
according to [comments in commit 03fba167fe](https://github.com/red/red/commit/03fba167fe4161d245b0382ee7956ded0ca2d414#r33854967) .
=> cleanup old unnecessary code

environment/actions.red
Added TBD to `compare` as for [this](https://github.com/red/REP/issues/48#issuecomment-493783537)  comment.
=> Added TBD to sort/compare with block

environment/console/GUI/core.red, modules/view/backends/gtk3/events.reds, modules/view/backends/gtk3/gtk.reds, modules/view/backends/gtk3/gui.reds, modules/view/backends/gtk3/handlers.reds, modules/view/backends/gtk3/text-box.reds
Known little issue: window needs to be resized at first to have caret properly drawn.
=> Gtk: starting caret and scrolling on gui-console

tests/source/units/regression-test-red.red
tricky macros
figured I'd fix the interpreter behavior on these as well while I'm at it...
main tests are in the PR #3781
=> interpreter tests for issue #3773

environment/console/GUI/core.red, environment/console/GUI/gui-console.red, modules/view/backends/gtk3/comdlgs.reds, modules/view/backends/gtk3/draw.reds, modules/view/backends/gtk3/events.reds, modules/view/backends/gtk3/font.reds, modules/view/backends/gtk3/gtk.reds, modules/view/backends/gtk3/gui.reds, modules/view/backends/gtk3/handlers.reds, modules/view/backends/gtk3/text-box.reds
Fix caret issue and also offset for window used in console-cfg.red
=> Gtk: Workaround for caret issue when first shown in gui-console

modules/view/backends/gtk3/comdlgs.reds, modules/view/backends/gtk3/gtk.reds, modules/view/backends/gtk3/gui.reds
This PR makes `tests/cursor.red` working. Cursor is also used in `gui-console`.
=> Gtk: Complete work on cursor

boot.red, build/includes.r, environment/codecs/csv.red, tests/source/units/csv-test.red
CSV codec with `load-csv` and `to-csv` functions.
See https://github.com/red/red/wiki/CSV-codec for detailed documentation.
=> FEAT: CSV codec added

environment/console/engine.red
test relative issues:
#1907 pass
#1991 pass
#1775 pass
#1995 pass
#2104 pass
#2050 pass
#2109 pass
#1147 pass
#2145 pass
=> FIX: issue #2573 (unmatched multiline end character in block doesn't rise error)

runtime/clipboard.reds
It is very annoying when I press `Ctrl+C` in GUI console, then `Ctrl+V` to paste the snippet into a different place - only to see that it pasted something else entirely and hopelessly messed the code...
**Summary**: This fix reduces clipboard failure rate from 10-15% to around 0.0001% (which I find acceptable) by trying OpenClipboard up to three times in a row, yielding the thread's time slice between attempts.
**More info** about #3778 problem:
The MS docs say in multiple places: 
> Before calling EmptyClipboard, an application must open the clipboard by using the OpenClipboard function. If the application specifies a NULL window handle when opening the clipboard, EmptyClipboard succeeds but sets the clipboard owner to NULL. Note that this causes SetClipboardData to fail.
I do not …
=> FIX: more robust fix for issue #3778

README.md, usage.txt
Document the --catch CLI option.
=> Add --catch to CLI usage documentation

modules/view/backends/windows/draw.reds
Fixes #3165 
The fix is a bit broad, but what else can we do :)
=> FIX: issue #3165 (Cannot drag face when display is scaled)

modules/view/backends/windows/draw.reds
Fixes #3225, using @Zamlox's commit 40a997e (thanks ☺)
=> FIX: issue #3225 (TEXT in DRAW does not honour TRANSLATE command)

runtime/datatypes/function.reds, tests/source/units/regression-test-red.red
Fixes #3362 (interpreter only, compiler doesn't work with that pattern at all anyway)
=> Issue 3362 fix

system/utils/libRedRT-exports.r
=> FIX: libRedRT export string/load-at

environment/actions.red
as discussed at gitter: https://gitter.im/red/docs?at=5dadc2739825bd6baca0d166
=> remove object! from find's docstring; see commit 7b1eeb76

modules/view/backends/gtk3/draw.reds, modules/view/backends/gtk3/events.reds, modules/view/backends/gtk3/gtk.reds, modules/view/backends/gtk3/gui.reds, modules/view/backends/gtk3/handlers.reds, modules/view/backends/gtk3/text-box.reds
=> support transparent

modules/view/backends/windows/gui.reds
Test snippet:
`view [a: area "Some^/line^/here" button "Show" [print [length? a/text a/selected]] button "SEL" [a/selected: 1x0 + any [a/selected 0x1] print [length? a/text a/selected]]]`
=> FIX: issue #3563 (Line-breaks in area on Windows add...)

tests/source/view/base-self-test.red
Closes #4116 
Contains tests for part 1 of #3725 and regressions that have not become issues
Plus some cosmetic changes and algorithm extensions
=> TESTS: base-self-test now covers #4116 and a bit of #3725

runtime/datatypes/structures.reds, runtime/natives.reds, runtime/platform/POSIX.reds, runtime/platform/win32.reds
removes OS dependency from `runtime/natives.reds`
=> CHORE: refactor `wait` native

modules/view/VID.red
https://github.com/red/red/issues/4211#issuecomment-569877021
=> FIX: issue #4211 (Deep reactor works improperly with dynamically...)

modules/view/backends/windows/gui.reds, modules/view/backends/windows/win32.reds
=> FIX: issue #4221 ([View] Screenshots do not contain layered windows)

build/includes.r
=> FIX: missing calendar.reds in PR #4225

modules/view/backends/gtk3/events.reds, modules/view/backends/gtk3/handlers.reds
See https://github.com/red/red/pull/4277 for details.
=> FIX: remove redundant signal handler

modules/view/backends/gtk3/draw.reds
=> FIX: radial gradient issues

modules/view/backends/windows/events.reds
=> FIX: issue #4338 (Asynchronous keyboard handler discards mod keys)

environment/actions.red, lexer.r, runtime/datatypes/binary.reds, runtime/datatypes/float.reds, runtime/datatypes/integer.reds, runtime/datatypes/money.reds, runtime/datatypes/pair.reds, runtime/datatypes/time.reds, runtime/natives.reds, tests/source/units/money-test.red
* Support for custom currencies;
* `round`;
* Refined conversion and construction.
=> FEAT: continued work on MONEY! datatype

runtime/datatypes/float.reds, runtime/datatypes/money.reds, runtime/natives.reds, tests/source/units/money-test.red
Includes finished `random` with some polishing here and there.
=> FEAT: completed work on MONEY! datatype.

runtime/datatypes/tuple.reds
Fixes #4215. Tests can be added later if needed.
=> FIX: issue #4215 (`tuple/make-rgba` makes a reversed tuple)

docs/red-system-specs.txt, environment/actions.red, runtime/datatypes/date.reds, runtime/datatypes/float.reds, runtime/datatypes/integer.reds, runtime/datatypes/logic.reds, runtime/datatypes/pair.reds, runtime/datatypes/series.reds, runtime/datatypes/tuple.reds, runtime/natives.reds, runtime/random.reds, runtime/red.reds, system/runtime/libc.reds, tests/source/units/integer-test.red, tests/source/units/series-test.red
Based on `crypto/urandom'. [Chat @ Gitter](https://gitter.im/red/blockchain?at=5e4e388d0c4514126679983b)
=> FEAT: random/secure

modules/view/utils.red
See https://github.com/red/red/commit/f4641e8d325da391ca8657817b258a2a7666e4be#r37001420
=> FEAT: scale hex-to-rgb to full intensity range

tests/source/units/regression-test-red.red
regression test for #4205 - seed random with precise time!
In addition to PR #4297.
fixed & force-pushed.
=> TESTS: regression test for #4205 - seed random with precise time!

build/includes.r, modules/view/backends/macOS/draw.reds, modules/view/backends/windows/draw.reds, runtime/datatypes/image.reds, runtime/image-utils.reds, runtime/vector2d.reds
like:
```
view [base 600x600 draw [image img 100x100 300x80 50x350 400x400]]
view [base 600x600 draw [image img 100x100 300x80 50x350]]
```
=> FEAT: support image! to Arbitrary quadrilateral

runtime/datatypes/string.reds
Those fixes are from PR #4097.  @hiiamboris 👍
=> FIX: issue #4432 ([CRASH] involving Parse, Reduce & GC)

tests/source/view/base-self-test.red
@9214 can you please test if this fix is working for you?
=> FIX: tests for #3725 were failing on W10

runtime/datatypes/series.reds, runtime/hashtable.reds, system/runtime/common.reds
=> FIX: issue #4511 (CHANGE arbitrarily thrashes hash! table)

runtime/lexer.reds
=> FIX: utf8-buf-tail is wrong in scan-alt function.

runtime/datatypes/bitset.reds, tests/source/units/bitset-test.red
Fixes #4378 by implementing @qtxie's proposal #4378 (comment), which is in line with the behavior of the rest of the datatypes. Tests are provided.
=> FIX: issue #4378 (make bitset! <float> gives strange result).

environment/natives.red
Resolves #4469 and addresses the points made in that issue.
=> FEAT: improve docstrings of conditional natives.

environment/networking.red
=> FIX: #4242

modules/view/VID.red
=> FIX: Don't eat STYLE keyword in style definition

compiler.r, tests/source/compiler/regression-test-redc-5.r
=> FIX: issue #3624

environment/functions.red, tests/source/environment/functions-test.red
=> FIX: CLEAN-PATH works properly with URL!

.github/ISSUE_TEMPLATE/bug_report.md
Proposes a slightly modified issue template for bug reporting.
=> FEAT: refine the issue template.

build/README.md
Corrects the outdated link to the README section.
=> FIX: update link to building instructions.

tests/source/units/draw-test.red
https://github.com/red/red/issues/3649#issuecomment-448567213
=> FIX: removed leftover conditions after #3649 was fixed

compiler.r, system/utils/libRedRT-exports.r, tests/source/units/loop-test.red, tests/source/units/regression-test-red.red
Fixes #3361 by keeping the real counter on the stack, rather than in a global variable
=> Issue 3361 fix

tests/source/compiler/regression-test-redc-5.r
Resolves the havoc wrecked by https://github.com/red/red/pull/4688.
=> FIX: fix non-passing issue #4613 regression test.

tests/source/compiler/regression-test-redc-5.r
Per https://github.com/red/red/issues/4568#issuecomment-717389684.
=> TESTS: add regression test for issue #4568.

tests/source/compiler/regression-test-redc-5.r
Per https://github.com/red/red/issues/4569#issuecomment-717353686.
=> TESTS: add regression test for issue #4569.

tests/source/compiler/regression-test-redc-5.r
Per https://github.com/red/red/issues/4570#issuecomment-717376664.
=> TESTS: add regression test for issue #4570.

README.md
See https://github.com/red/red/pull/4704.
=> FEAT: synchronize README with USAGE.TXT content.

environment/codecs/BMP.red, environment/codecs/GIF.red, environment/codecs/JPEG.red, environment/codecs/PNG.red, runtime/natives.reds, runtime/platform/image-gdk.reds, runtime/red.reds
Fix issue #4698 and issue #4700.
=> FEAT: enable image! in red/core on Linux

modules/view/backends/platform.red, tests/source/view/base-self-test.red
It succeeds on my W10, but when it prints report and is about to quit, the console hangs as in https://github.com/red/red/issues/4184 - by infinitely scrolling itself.
=> base-self-test fixes and more

runtime/simple-io.reds
=> FIX: issue #4794 (PUT & DELETE requests CRASH on Linux)

environment/console/help.red
=> Fix truncated typeset output.

environment/console/help.red
imagine how often I'm doing this manually ;)
=> FEAT: auto copy about text to clipboard

environment/functions.red
As [discussed on Gitter red/red channel](https://gitter.im/red/red?at=60833314ae90f368409cd70b).
=> FIX: cleaner to-red-file non-windows implementation

runtime/platform/image-wic.reds
A cosmetic change. WIC was not clear for me.
=> FEAT: explain WIC acronym

red.r
Resolves #4095. Also refer to recent [red/bugs gitter chat](https://gitter.im/red/bugs?at=606c2cc60147fb05c5dcea6e).
=> FIX: issue #4095 (quit-return does not impact return code of red binary)

runtime/datatypes/bitset.reds, runtime/datatypes/date.reds, runtime/datatypes/float.reds, runtime/datatypes/word.reds, tests/source/units/find-test.red, tests/source/units/select-test.red
=> FIX: Issue #4165

runtime/macros.reds, system/compiler.r, system/emitter.r, system/targets/ARM.r, system/targets/IA-32.r, system/tests/float-matrix-manual.reds, system/tests/nan-tests-manual.reds, system/tests/nan-tests-manual32.reds, system/tests/source/units/float-test.reds, system/tests/source/units/float32-test.reds, tests/source/units/regression-test-red.red
See PR #3902
Fixes #847, fixes #2567
=> IEEE-754 compliance in float comparison operators

environment/actions.red
Complementary update on find help
=> FIX: issue #4943 (FIND/match/tail overshoots on lists)

environment/actions.red
=> FIX: issue #4956 (Restores parity between all hashable values and PUT's type signature.)

environment/console/help.red
I was going to call this branch Gregg-hates-git but...
=> Add trace/no-trace attrs to func spec parser.

environment/tools.red
3rd variant, proposed by Gregg
=> FEAT: high level tracer

tests/source/units/date-test.red
=> TESTS: for issue #5033 (Negative week day in BC dates)

runtime/platform/win32.reds, tests/source/units/regression-test-red.red
Fixes #5114 by declaring time machines illegal.
=> Issue 5114 fix

runtime/hashtable.reds, tests/source/units/regression-test-red.red
=> Issue 5126 fix

environment/routines.red, tests/source/units/routine-test.red
=> FIX for #5145

runtime/datatypes/map.reds
Seemed simple enough, though I'm not super experienced with R/S so I might've missed something
=> FIX: issue #5108 (Extra block copy in make map!)

environment/tools.red
https://github.com/red/red/issues/5189#issuecomment-1231626484
=> DOC: minor docstrings fix

runtime/datatypes/vector.reds
=> FEAT: vectors skip +-0 and */1 operations

tests/source/view/base-self-test.red
let's see what the hell is going on there, will revert later
=> TESTS: temporary test commit

tests/source/view/base-self-test.red
=> TESTS: trying increased timeout

environment/functions.red
=> FEAT: unboring also

environment/functions.red
https://github.com/red/red/pull/5327
=> FEAT: Unboring attempt (fixed)

environment/tools.red, tests/source/units/evaluation-test.red
All kludges of the early implementation removed now. Simplified code. Works with exceptions (throw/error). Preserves the look of original data from modifications, so beginner friendly. A test suite added to avoid regressions.
=> FEAT: Improved high level tracer

tests/source/view/base-self-test.red
Reverts red/red#5290
and increases timeout to what seems to have worked
=> Revert 5290 bst debug

tests/clip-point-test.red, tests/complexpen-point-test.red, tests/draw-point.red, tests/matrix-point-test.red, tests/shape-point-test.red, tests/shield-point.red
just replaced pairs with points, to test Draw support for point2D
some tests seems outdated though even in their original form, e.g. `matrix-test.red`
=> TESTS: Draw tests with point2D for pairs

environment/system.red
=> FIX: switch codecs to a map again

build/includes.r, environment/console/CLI/POSIX.reds, runtime/call.reds, runtime/crypto.reds, runtime/platform/POSIX.reds, runtime/platform/image-stub.reds, runtime/red.reds, runtime/simple-io.reds, runtime/threads.reds, system/config.r, system/runtime/lib-names.reds, system/runtime/start.reds
Limitations:
1. No checksum
2. No image!
=> FEAT: add Pico config for embedded Linux ARM

runtime/datatypes/bitset.reds
Having another go here, somehow managed to deface pr https://github.com/red/red/pull/5556
=> FIX: added missing same? arg to bitset find

environment/codecs/CSV.red
=> FIX: issue #5639 correct /as-record doc string.
