- runtime/actions.reds
- runtime/datatypes/string.reds
FIX: incorrect result when doing not-equal op! on different types.
> FIX: incorrect result when comparing two strings.

- environment/console/input.red
- environment/console/win32.reds
Using Ctrl-C and Ctrl-D to exit console.
> FEAT: handle ctrl-c and ctrl-d in new-console

- environment/console/input.red
FIX: better handling for Ctrl-C and Ctrl-D.
> FIX: issue #1020 (Console eats TAB character in a pasted input line)

- quick-test/quick-test.r
Made this because I get tired of manually having to manually modify quick-test.r in order to get tests to run on my Windows machines.  Most of uses of `call` were equivalent, and I modified the only unique one to `/output` to an anonymous buffer.
> TESTS: Create a switch for running CALL with /SHOW or /WAIT

- environment/console/POSIX.reds
- environment/console/input.red
- system/runtime/POSIX.reds
```
struct sigaction {
void     (*sa_handler)(int);
void     (*sa_sigaction)(int, siginfo_t *, void *);
sigset_t   sa_mask;
int        sa_flags;
void     (*sa_restorer)(void);
};
```
If SA_SIGINFO is specified in sa_flags, then sa_sigaction (instead of sa_handler) specifies the signal-handling function for signum.
As we use `sa_handler` here, we don't need to set the ` SA_SIGINFO ` flag.
> FIX: issue #1098 (OSX: red console crash upon window resize)

- environment/console/input.red
This change in input.red makes it possible for users to reuse the code in %input.red for their own projects, adding 'ask functionality to their console programs by adding #include for this file
> FEAT: temporary patch to allow inclusion of %input.red in user code.

- environment/natives.red
- runtime/datatypes/block.reds
- runtime/datatypes/native.reds
- runtime/natives.reds
FEAT: added set operations for hash! datatype
Note: when one of the two arguments is hash datatype, the set function always returns a hash.
> FIX: issue #1243 (union with /skip refinement gives incorrect results)

- runtime/datatypes/block.reds
- runtime/datatypes/hash.reds
- runtime/datatypes/map.reds
- runtime/datatypes/series.reds
- runtime/hashtable.reds
- runtime/red.reds
New hashtable API:
```
;-- hashtable/init num-of-buckets null HASH_TABLE_INTEGER num-of-values
table: _hashtable/init 16 null HASH_TABLE_INTEGER 2
;-- Put value:
value: as cell! _hashtable/put-key table 0045A387h
copy-cell as cell! str value
copy-cell as cell! int (value + 1)
;-- Get value:
value: as cell! _hashtable/get-value table 0045A387h
str: as red-string!  value               ;-- value 1
int: as red-integer! value + 1           ;-- value 2
```
> FEAT: support integer key in hashtable

- docs/red-system-specs.txt
Minor update to Red/System Language Specification to remove Float32! from the list of types allowed in a literal array.
> DOCS: Remove Float32! from list of values allowed in literal arrays

- environment/functions.red
without fix:
```rebol
load http://domain/source.red
*** Script error: transcode does not allow url for its <anon> argument
*** Where: transcode
```
with fix:
```rebol
load http://domain/source.red
;   [Red [] print 123]
```
```rebol
system/platform
;   MacOSX
```
> Fix: allow loading url! of type not image! on non Windows platforms

- environment/natives.red
- runtime/macros.reds
- runtime/natives.reds
- runtime/platform/POSIX.reds
- runtime/platform/win32.reds
Note: the granularity of `wait` is millisecond.
> FEAT: added preliminary support for WAIT native

- build/build.r
build script just checks to see if the sdk path setup was properly created before building.  
if not:
-it prompts user
-copies sample file
-allows him to edit file by pausing build.
-allows him to continues build by pressing enter in the main build window.
> added check and prompt for Rebol SDK setup.

- runtime/datatypes/pair.reds
Before this fix:
```
red>> make pair! [2.1 3.456]
*** MAKE Error: pair expects a block with two integers
== -858993459x1408749273
red>> 2x2 + 'c
*** Math Error: unsupported right operand for pair operation
== 4408243x2
red>> make pair! 1.2
*** Runtime Error 1: access violation
*** at: 0041A6ECh
```
With this fix:
```
red>> make pair! [2.1 3.456]
*** Syntax error: invalid construction spec: 2.1 3.456
*** Where: make
red>> 2x2 + 'c
*** Script error: word type is not allowed here
*** Where: +
red>> make pair! 1.2
*** Script error: 1.2 type is not allowed here
*** Where: make
```
> FIX: improving make pair! asserts

- runtime/datatypes/float.reds
- runtime/datatypes/tuple.reds
- runtime/datatypes/vector.reds
Note: now the convertion will round the float number to nearest number.
This is different from Rebol, which will truncate the float number.
I think we need R/S support to get truncation work correctly.
> FIX: issue #1542 (incorrect conversion from odd whole float! to integer)

- modules/view/backends/windows/base.reds
- modules/view/backends/windows/gui.reds
Layered window as child window on windows version above Win 7 has some odd
behaviours. see issue #1635 and issue #1604.
FIX: unfocus parent window when click a base window.
> FEAT: always create layered window as a POP_UP window.

- environment/console/input.red
Ctrl-K will erase to end of line.
Ctrl-D will remove character or exit like Ctrl-C if empty line.
> console: better support for Ctrl-K and Ctrl-D.

- system/library/curses/curses.reds
- system/library/curses/examples/curses-example.reds
As I can see variables defined within functions are no more global ones in Red > 0.6.0. This behaviour has slightly broken the curses library binding (and helped to find two typos).
Also I'm not sure about the initial value of stdscr, so for now it's just zero.
> Some variable scope policy fixes in the curses binding

- modules/view/VID.red
In fetch-options:
fetch-argument must behave similarly to fetch-value
Allow:
view [base 100x100 draw my-obj/my-block]
used for draw,font,para,font-name,font-color,font-size,react
> MISS: allow path! for some options in VID dialect

- runtime/interpreter.reds
A vicious one which occurs in interpreted code sometimes, and disappear as soon as you try to debug it.
It literally took me hours to figure it out in my failing code... T_T
Red>> (a: 'ok 1 :a)
== ok
Red>> (a: 'ok 1 + 1 :a)    ; NOT OK
== 2
Red>> (a: 'ok 1 + 1 probe :a)
ok
== ok
> FIX: Interpreter skip get-word! as return value

- environment/natives.red
- environment/routines.red
- runtime/crypto.reds
- runtime/natives.reds
There is some refactoring that could be done in %natives.reds and condensing the %crypto.reds CRC/MD5/SHA* funcs to take an alg type arg.
> Added SHA 256/384/512 support (Windows only).

- runtime/crypto.reds
Byte was carrying sign in TCP, and SHA384/512 needed a different block size.
> Fixed TCP and SHA384/512 HMAC.

- modules/view/backends/windows/events.reds
FIX: do not create moving event when minimize window
> FIX: issue #2052 (gui-console can't be closed from task bar)

- utils/call.r
This makes it R2 compatible, as a drop-in replacement for CALL.
> FEAT: Now returns process exit code and delines 'out and 'err.

- system/compiler.r
- system/utils/libRed.r
Changed absolute paths to relative, so it works regardless of where the red source folder is.
If this isn't what you were intending to do, feel free to close it.
I did this partly to understand how github pull requests work (so a simple change)
> FIX: change write paths to relative for libred

- modules/view/backends/windows/draw.reds
- modules/view/backends/windows/win32.reds
- modules/view/draw.red
Basic clip command for draw dialect. It clips a rectangle area specified by coordinates:
```
clip <top-left> <bottom-right>
<top-left>     : coordinates of the top-left of the box (pair!).
<bottom-right> : coordinates of the bottom-right of the box (pair!).
```
If a sub-block follows clip command, it will affect only that sub-block.
Example:
```
view [base 200x200 draw [ clip 10x10 50x50 box 10x10 100x100]]
view [base 200x200 draw [ clip 10x10 50x50 [box 10x10 100x100] box 20x20 100x100]]
```
It can be extended later for non-rectangle areas.
> FEAT: Added 'clip' command for 'draw' dialect

- modules/view/backends/windows/draw.reds
- modules/view/draw.red
Allow passing ```float!``` type values for following shape commands:
- vline
- hline
- arc
> Shape dialect improvements

- modules/view/backends/windows/draw.reds
- modules/view/backends/windows/win32.reds
- modules/view/draw.red
Following improvements have been done:
- FEAT: Shape - preserve last point among different shape blocks
Last point of a shape block will be saved and used as start point for next shape block within same draw block if no 'move' command used before using one of drawing shape commands. This might be useful when drawing one shape requires changing different graphic attributes (pen, fill, width). In this case shape block can be split and next shape block can continue from where it stopped previous block.
- FEAT: Draw - Improve clip command
Clip command have been improved by allowing to clip a region (given by a path), not only a rectangle. The region can be specified as a block of shape commands, like:
```
view [base 200x200 draw [clip [move 80x120 'arc 1x1 30 30 0 large sweep] fill-pen red …
```
> Improvements on shape and draw

- modules/view/backends/windows/draw.reds
- modules/view/backends/windows/win32.reds
- modules/view/draw.red
Following improvements have been done:
- 	**_FEAT: Draw - added clip mode_**: an optional parameter have been added to draw ```clip``` command. It can have following values: ```replace```, ```intersect```, ```union```, ```xor``` and ```exclude```. By default the value is ```replace```. Once set a clip mode, it will persist even if ```clip``` command is called without this optional parameter. Clip mode changes only when explicitly set.
- 	**_FEAT: Draw - added matrix-order command_**: an additional command have been added to ```draw``` dialect: ```matrix-order```. It can have following values: ```append```, ```prepend```. It tells the system how to order matrix multiplications for transformation commands. ```append``` will add the transformation matrix on the right side of multiplication …
> Draw and shape improvements

- modules/view/backends/windows/draw.reds
- modules/view/draw.red
**_FIX: Draw - rotation center updated with world transformation matrix_** - update rotation center with world transformation matrix
**_FIX: Draw - move GDI+ dependent code to draw.reds_** - move GDI+related code from ```draw.red``` to ```draw.reds```
**_FIX: Draw - remove system/words from trigonometric functions call_** - removed prefix ```system/words``` from trigonometric functions call
> Draw fixes

- build/README.md
Since people keep asking this question. As this is temporary, when the time comes, this message and the SDK requirement can be removed. So I don't see any reason not to add this note.
The wording could be improved tho
> FIX: Clarify Rebol SDK is not needed for sources

- modules/view/VID.red
To my understanding, only `font/style` facet needs to be handled as a `block!` if several styles words are provided.
No other facet in `font!`, nor `para!` object has to handle more than one value.
With the exception of `/state` and `/parent` maybe, but there are managed by low level code AFAIK, not by VID functions.
It must fixe #2269 and fixe #2380
> 'add-flag only handle font/style as block!

- modules/view/backends/windows/draw.reds
There is an issue with colors position for radial gradient when they are not specified in draw dialect. This commit will fix that issue.
> FIX: Draw - radial gradient colors position

- environment/functions.red
- tests/source/units/series-test.red
This PR fixes infinite loop problem for `replace/all "abab" #"a" #"a"`
> FIX: Replace function infinite loop problem

- runtime/platform/win32-ansi.reds
- runtime/platform/win32-cli.reds
This modification enables ANSI escape sequences to be processed in the Windows CLI console. It would be probably fine to add at least cursor support into `gui-console` while stripping the escape sequences there when not applied (gui console cannot have colors).
> FEAT: basic support for ANSI escaping sequences in Windows CLI console

- environment/natives.red
- runtime/natives.reds
Now it is possible to use `time!` to represent time.
```
>> t: now/time/precise wait 0:0:0.1 now/time/precise - t
== 0:00:00.100000001
>> t: now/time/precise wait 42:0:0.01 now/time/precise - t
== 42:00:00.010000001
```
> FEAT: adding support for `time!` as an argument for `wait` native

- system/assets/macOS/Info.plist
macOS apps built by Red compiler are running in low resolution.
Reference: https://developer.apple.com/library/content/documentation/GraphicsAnimation/Conceptual/HighResolutionOSX/Explained/Explained.html
> FIX: HiDPI should be enabled on macOS.

- environment/functions.red
Reset indentation state between calls. Current output:
```
>> parse-trace [1 2] [2 number!]
-->
match: [2 number!] 
input: [1 2]   
-->
==> matched
match: [number!] 
input: [2]     
==> matched
<--
return: true
== true
>> parse-trace [1 2] [2 number!]
-->
match: [2 number!] 
input: [1 2]     
-->
==> matched
match: [number!] 
input: [2]       
==> matched
<--
return: true
== true
>> parse-trace [1 2] [2 number!]
-->
match: [2 number!] 
input: [1 2]       
-->
==> matched
match: [number!] 
input: [2]         
==> matched
<--
return: true
== true
```
> Fix parse-trace indentation issue

- environment/functions.red
Small step for the Red, but huge crawl for a toddler. :baby_bottle:
> FIX: issue #2969 (Doc-string wrongly placed in `what-dir` function)

- environment/functions.red
Currently it just uses exit and fails silently.
> Added error for unsupported save/as formats

- red.r
- system/utils/libRedRT-exports.r
**FIX: added two functions to export list: decode-utf8-char and form-signed**
- this commit adds two functions to the export list of libred. I couldn't compile red console on my Ubuntu 16.04 without this change
**FIX: issue #3196 (missing check for SSE3 instructions on Linux)**
- this commit will check for string "sse3" in /proc/cpuinfo using a parse rule and it will set SSE3? to true if it founds or false otherwise
> Add check for SSE3 instruction on Linux

- environment/functions.red
Changes `split` function's behavior as below:
```
>> split "a-b--" "-"
== ["a" "b" ""]  ; before
== ["a" "b" "" ""] ; after
```
> FIX: split function's return value was missing for consecutive delimiters

- build/build.r
> FIX: build.r script hangs on Rebol 2.7.8.3.1 (Windows)

- build/git-version.r
- docs/issue_template.md
- environment/console/GUI/settings.red
- environment/console/help.red
- use full size commit hash in `system/build/git/commit` (@rebolek)
- add `/debug` refinement to `about` to return values suitable for submitting issues
- use `system/build/git/date` instead of `system/build/date` in return of `about` command (the later is the date of the locally built console, toolchain build date more appropriate)
- use commit of length 7 for commit hash in `about`, compatible with GitHub website (@meijeru).
- use local zone for build date returned by `about` as this is not meant to be shared and more human friendly. `about/debug` uses UTC zone to not leak user zone info on GitHub issues.
- updated issue template, format debug versions string as code, we'll have a transitiong time where this has to be run `any [attempt[about/debug] about]` after which we will change the …
> feat: improvements on git version integration and new about/debug command

- environment/functions.red
`system/options/boot` was a `string!`. In Rebol it is a `file!`.
So make it as `file!` too for compatibility.
Edited in the browser, so not tested !
> Make system/options/boot as file! (not string!)

- runtime/datatypes/series.reds
Partial fix for edge case when `clear` or `remove` a series which points to another series's tail.
**`change` action also has the similar bug in such edge case, and I am working on it.**
@qtxie @bitbegin Please review this fix. Thanks!
> FIX: issue #3369 (accessing series over the board)

- environment/console/CLI/input.red
- environment/console/GUI/gui-console.red
- environment/console/GUI/old/gui-console.red
- environment/console/auto-complete.red
- environment/console/engine.red
- environment/functions.red
- environment/natives.red
- environment/routines.red
- modules/view/view.red
Added missing doc strings, #3413
```
<<                   : Shift bits to the left
>>                   : Shift bits to the right
>>>                  : Shift bits to the right (unsigned)
_read-input          : Internal Use Only
_set-buffer-history  : Internal Use Only
as-color             : Combine R, G and B values into a tuple
as-ipv4              : Combine a, b, c and d values into a tuple
as-rgba              : Combine a, b, c and d values into a tuple
ask                  : Prompt the user for input
bind                 : Bind words to a context; returns rebound words
charset              : Shortcut for `make bitset!`
comment              : Consume but don't evaluate the next value
common-substr        : Internal Use Only
construct            : Makes a new object from an unevaluated …
```
> Added missing doc strings, #3413

- environment/functions.red
- tests/source/environment/functions-test.red
no need to convert from url! to thru-cache dir structure
cache file is placed under path based on md5 checksum
>> path-thru http://www.red-lang.org/
== %/C/ProgramData/Red/cache/C3/C36ABFBA6FA8418E5BF6E31127F1DCFD
>> path-thru http://rowery.olsztyn.pl/?r=10
== %/C/ProgramData/Red/cache/B4/B4BCF480EF4282064228FDE953F255B7
Pijoter
> path-thru filename as md5 checksum

- environment/functions.red
- environment/natives.red
- modules/view/draw.red
- modules/view/view.red
Added doc strings of refinements for `bind`, `decompress`, `draw`, `link-tabs-to-parent`, `load`, `pad`, `parse`, `parse-trace` functions.
> Added doc strings for some refinements

- runtime/datatypes/logic.reds
- runtime/datatypes/none.reds
- tests/source/units/mold-test.red
This is a very simple change that implements the `/all` refinement for `mold` on `logic!` and `none!` values.
> Implemented MOLD/ALL for LOGIC! and NONE! values

- build/build.r
git.r file looks modified after each build on Windows because of line endings difference. Might be possible to ignore by changing git settings, but better to keep the original line endings.
> FIX: build/git.r file looks modified after each build on Windows

- environment/functions.red
- tests/source/environment/functions-test.red
Added SUM and AVERAGE functions.
See also [Design notes of SUM function](https://github.com/red/red/wiki/%5BDESIGN%5D-SUM-function)
> FEAT: Added SUM and AVERAGE functions

- environment/natives.red
UCT in NOW/ZONE doc string fixed to UTC
> FIX: Typo in NOW/ZONE doc string

- environment/console/GUI/core.red
```
a-an about absolute acos action! action? add alert all all-word! all-word? also alter and and~ any any-block! any-block? any-function! any-function? any-list! any-list? any-object! any-object? any-path! any-path? any-string! any-string? any-type! any-word! any-word? append aqua arccosine arcsine arctangent arctangent2 as as-color as-ipv4 as-pair as-rgba asin ask at atan atan2 attempt average
>> a
```
should be 
```
>> a-an about absolute acos action! action? add alert all all-word! all-word? also alter and and~ any any-block! any-block? any-function! any-function? any-list! any-list? any-object! any-object? any-path! any-path? any-string! any-string? any-type! any-word! any-word? append aqua arccosine arcsine arctangent arctangent2 as as-color as-ipv4 as-pair as-rgba asin ask at atan …
```
> FIX: prompt not be showed after do-completion

- runtime/datatypes/datatype.reds
- runtime/macros.reds
- runtime/red.reds
used a long and explicit macro name (```TYPE_TOTAL_COUNT```) so it doesn't get mixed up with a type name within code.
```
TYPE_COUNT    TYPE_MAX   
```
could look like data type names and not be as obvious in intent.
> FEAT: use macro to automatically track number of datatypes in all code

- environment/functions.red
`case` refinement added to `replace` function. See https://github.com/red/REP/issues/18
```
>> replace/all/case/deep quote (a (A a (A a))) ['a] 'x
== (x (A x (A x)))
```
> FEAT: Added case refinement to REPLACE function

- runtime/datatypes/error.reds
- runtime/natives.reds
- tests/source/compiler/compile-error-test.r
- tests/source/units/all-tests.txt
- tests/source/units/try-test.red
It did not crash, just exited silently, as R/S part believed that Red part has displayed the error already:
https://github.com/red/red/blob/master/system/runtime/common.reds#L258
On a side note: it's debatable if returning `0` after a Red error is a good idea. @dockimbel what do you think?
Then, Red part executed `try [break]` like this:
- `throw-break` couldn't find the *loop frame*, so it called `throw-error` to throw a Red error https://github.com/red/red/blob/master/runtime/stack.reds#L446
- `throw-error` was finding the *try frame* https://github.com/red/red/blob/master/runtime/stack.reds#L399 and threw an R/S error https://github.com/red/red/blob/master/runtime/stack.reds#L415
- `try*` was catching that R/S error https://github.com/red/red/blob/master/runtime/natives.reds#L1923 and …
> Fix for #3268

- runtime/datatypes/image.reds
- tests/source/units/image-test.red
Apparently there's no integer-to-pixel assignment yet. It just allows to assign anything:
```
>> poke im 1 "junk"
== "junk"
>> im/1: 'junk
== junk
>> im/1
== 132.56.50.0
```
I added a type check and a couple of tests.
New behavior for everything but tuples:
```
>> i/1: "junk"
*** Script Error: invalid argument: "junk"
*** Where: set-path
*** Stack:  
```
> FIX for #3582

- modules/view/backends/macOS/gui.reds
- modules/view/backends/windows/gui.reds
This formula
```
delta: either dpi-factor = 100 [0][1]
....: size/width * 100 / dpi-factor + delta
``` 
relies on 2 assumptions:
- (size/width * 100) / dpi-factor never becomes an integer
- dpi-factor is always <= 100
Both don't look valid to me. I suggest just round the result to the nearest higher integer.
> proper ceiling in size-text

- quick-test/quick-test.red
I added this flag when using `quick-test.red` as otherwise it was impossible to know at which test it crashes or complains. Let it be in the repo, ok? @PeterWAWood 
Usage: add `qt-verbose: yes` after the #include of quick-test.red.
> FEAT: qt-verbose flag

- modules/view/view.red
`do-events` doesn't work on CLI console:
```
>> do-events
*** Script Error: path none is not valid for none! type
*** Where: eval-path
*** Stack: do-events
```
This PR fixes `do-events` to return `none` on CLI instead of error above.
> FIX: do-events returns error on CLI console

- modules/view/VID.red
- modules/view/backends/macOS/gui.reds
- modules/view/backends/platform.red
- modules/view/backends/test/gui.reds
- modules/view/backends/windows/base.reds
- modules/view/backends/windows/draw.reds
- modules/view/backends/windows/events.reds
- modules/view/backends/windows/gui.reds
- modules/view/backends/windows/para.reds
- modules/view/backends/windows/win32.reds
- tests/base-self-test.red
- tests/run-all.r
- tests/source/view/base-self-test.red
Wow it got the tests passed ☺
OK. This is a Windows-related fix, mostly W7-related.
@qtxie @greggirwin and @PeterWAWood please review this one.
Basically this was meant to fix 3 things:
1) text alignment on ~~all your~~ base face https://github.com/red/red/issues/2503#issuecomment-447576716
2) `to-image` inability to capture tricky layered W7 base faces https://github.com/red/red/issues/3465
3) make `size-text` results somewhat relevant to the actual text displayed, with multi line support
**Brief summary of changes and findings:**
- Pursuing (1) I had to drop GDI text rendering in favor of GDI+.
- Pursuing (2) I had to also use GDI+ for background rendering, as older GDI parts are totally unaware of the alpha channel and thus FillRect's output is transparent from AlphaBlend's point of …
> layered base fixes & tests

- README.md
The page was moved during wiki reorganization.
> FIX: missing link to contribution guidelines

- modules/view/RTD.red
1) To prevent `underline` or `strike` to be positioned immediately before color-tuple, let's transfer color-setting before other styles in `pop-all`.
```
pop-all: function [mark [block!]][
first?: yes 
if col [pop-color] ; <-- TO HERE
while [mark <> tail stack][
pop last stack
either first? [first?: no][remove skip tail out -2]
]
;if v [pop-color] FROM HERE --^
]
```
2) Notice that `v` is changed to `col` above. That's because `v` is set to `none` on each style in path (line 46 below) and so color was not added if it appeared in earlier places in path. To fix it I introduced new flag `col`, which is set to `none` just once while entering path (line 45), and to `yes` if color is seen in the styles path (line 48).
```
| ahead path!
into [
(col: none mark: tail stack) some [ ; <-- LINE 45 …
```
> Fix optimization phase and `s`/`u` strange behaviour in RTD

- modules/view/RTD.red
Currently, if colors which where open in the beginning are closed in the end then other colors which where inserted in between are overwritten. Like this:
```
view [rich-text data [
"black " red "red " green ["green " blue ["blue "]] "red"
]]
```
[![rt-colors-1](http://vooglaid.ee/red/rt-colors1-1.png)](http://vooglaid.ee/red/rt-colors1-1.png)
To prevent this, unclosed colors should be inserted in the beginning of the out block in `close-colors`:
```
close-colors: has [pos][
pos: tail color-stk
while [pos: find/reverse pos '_][
pos/1: tail-idx?
insert out as-pair pos/-1 tail-idx? - pos/-1
insert next out pos/2
new-line skip out 2 on
pos: remove/part skip pos -1 3
]
]
```
The above rich-text snippet will show better with this change, but not perfect, because similar problem affects colors …
> Fix: Order of colors in RTD

- environment/functions.red
- environment/natives.red
- runtime/natives.reds
- tests/source/units/float-test.red
So I was asleep when my mind brought it up to me that there was a typo in the previous docstrings. And then @greggirwin wished to also modify docstrings of corresponding natives. And then I noticed that arctangent2 was definitely meant to support radians, yet never implemented:
- otherwise it is meaningless to have atan2 and arctangent2 doing the same thing under 2 names
- https://github.com/red/red/blob/c87d85e8e7fbfb6b753538971e3ddfa8345cae9c/runtime/natives.reds#L1702 (presence of a check for nonexistent argument)
- https://github.com/red/red/blob/c87d85e8e7fbfb6b753538971e3ddfa8345cae9c/environment/functions.red#L984 (passing of `1` into nowhere as only a single arg is accepted)
Then I thought what's the better time than now... ;)
>  arctangent2 radians/degrees support 

- modules/view/RTD.red
Color-tuple should stay just after range when uniting styles, as explained by @qtxie in https://github.com/red/red/issues/3691
Also: Count colors in path (may be multiple colors in path, last is rendered), fixed new-line for `close-colors`.
> FIX: Unite colors in right order

- environment/functions.red
- modules/view/view.red
- tests/source/environment/functions-test.red
This PR fixes the `replace` with a `tag!` value issue discussed [here](https://gitter.im/red/help?at=5c2e82bfbabbc178b2222348)
Other commits appear in this PR are already merged, so it is safe to merge. The reason explained here [GitHub pull request showing commits that are already in target branch
](https://stackoverflow.com/questions/16306012/github-pull-request-showing-commits-that-are-already-in-target-branch)
> Issue 3703

- modules/view/RTD.red
Still more fixes on RTD. Currently nested style-paths are not allowed. Or rather, only innermost styles (except color) of nested style-paths end up in low-level data, like this:
```
view [rt: rich-text data [
u/red ["red underline " i/s/b/gold ["italic strike bold underline gold"] " red underline"]
]]
```
[![rt-colors4-1](http://vooglaid.ee/red/rt-colors4-1.png)](http://vooglaid.ee/red/rt-colors4-1.png)
Let's make pop-color counters and pop stack "nested-conscious" by introducing two more stacks: one for `mark` and the other for color counters ([line 17](https://github.com/red/red/blob/master/modules/view/RTD.red#L17)):
```
mark: copy [] col: 0 cols: copy []
``` 
Then, use these on [lines 46 - 52](https://github.com/red/red/blob/master/modules/view/RTD.red#L45):
```
| ahead path!
into [ …
```
> FIX: Allowed nested style-paths

- environment/reactivity.red
- tests/source/units/reactivity-test.red
I was annoyed by this behavior:
```
r: make reactor! [set 'r self a: none react/later [print [r/a r/a r/a]]]
>> r/a: 1
1 1 1
1 1 1
1 1 1
== 1
```
New behavior:
```
>> r/a: 1
1 1 1
== 1
```
> basic dupe check for reactivity

- CONTRIBUTING.md
Per @dockimbel's recent remark.
> FEAT: describe prefixing convention for commit messages

- environment/natives.red
- tests/source/units/object-test.red
This PR fixes the regression of using `get` on `object!` values that should return the values of the given object.
```
og1: make object! [a: 1 b: 2 c: "x"]
>> get :og1  ;before the PR
*** Script Error: get does not allow object! for its word argument
>> get :og1  ;after the PR
== [1 2 "x"]
```
> FIX: get on object! doesn't return values-of object (regression)

- modules/view/view.red
This PR fixes issue #3832 
```
>> view [fld: field all-over no-border do [? fld/flags]]
== FLD/FLAGS is a word! value.  all-over  ; << should be a block! [all-over no-border]
```
> FIX: Cannot give multiple flags in VID dialect

- modules/view/VID.red
This PR adds `password` flag to VID:
```
view [field password]
```
> FEAT: Added password flag to VID

- environment/functions.red
`charset` now supports `bitset!` and `binary!` arguments, per [`bitset!` implmenentation](https://github.com/red/red/blob/master/runtime/datatypes/bitset.reds#L531).
> FIX: issue #3853 (charset function not implements binary! type for argument)

- environment/console/engine.red
- environment/functions.red
- red.r
- runtime/utils.reds
Fixes #3581, fixes #2772, fixes #1773
This PR implements simple but correct CLI argument quoting/unquoting mechanics:
- on Windows following the CMD.EXE logic (only double quotes)
- on other platforms using single quotes
- **update**: also the "--" command line switch that marks the end of switch processing
**References:**
https://unix.stackexchange.com/a/357932
https://blogs.msdn.microsoft.com/twistylittlepassagesallalike/2011/04/23/everyone-quotes-command-line-arguments-the-wrong-way/
https://docs.microsoft.com/en-us/previous-versions//17w5ykft%28v=vs.85%29
https://github.com/red/red/issues/2772#issuecomment-440485682
**Tests**
I have only manually tested this using stuff I uploaded here: https://gitlab.com/hiiamboris/tests-files-3870
I don't have Rebol SDK (of course) so can't rebuild …
> FIX: issues #3581, #2772, #1773

- runtime/call.reds
Fixes #3869 
Adds `cmd /s /c` to a `/shell` call and wraps the command line in double quotes, fixing this scenario:
```
>> call/wait/shell/console {"prog ram" "" 1 "2 3"}    ;) adding /shell breaks everything
"prog" is not recognized as an internal or external command, operable program or batch file.
== 1
```
Another scenario
```
>> call/wait/console {prog ram "" 1 "2 3"}     ;) NO idea why this works - it should run `prog`
[prog ram] ["" 1 "2 3"]
-> [] [1] [2 3]
== 0
```
is not Red's fault, but a result of MS [CreateProcessW being smart](https://docs.microsoft.com/en-us/windows/desktop/api/processthreadsapi/nf-processthreadsapi-createprocessw) (how uncommon for those guys):
>  If you are using a long file name that contains a space, use quoted strings to indicate where the file name ends …
> FIX: issue #3869

- environment/console/engine.red
- red.r
Fixes the `--catch` problem that arose from PR #3870 :point_up: [May 16, 2019 10:12 AM](https://gitter.im/red/bugs?at=5cdd0d517c363c75a7ea6aff)
Also rewrote the argument joining function to be more reliable (it was pretty quick and dirty).
Now it is tolerant to filename abuses.
This is the test output on W7 (with the meaning of each argument denoted; also notice the `>> q` when `--catch` flag got transferred to (and eaten by) the console executable):
```
option option
> red.exe --cli --catch
--== Red 0.6.4 ==--
Type HELP for starting information.
>> q
option    script
> red.exe --cli -- --catch
BOOT=[C:\ProgramData\Red\console-2019-5-16-42230.exe] SCRIPT=[--catch] ARGS=[]
-> ARGLIST=
option option     script
> red.exe --cli --catch -- --catch …
```
> FIX: more complete patch for commit a7301b09 (PR #3870) fixing --catch

- runtime/natives.reds
- tests/source/compiler/print-test.r
Fixes #2047, fixes #2393
(so much boring stack trickery involved, makes me sick to even look at the code)
Test script:
```
print [1 2 print [ 5 ]]
print [1 2 print 5 ]
print print 5
print [1 2 prin 5]
prin [1 2 print 5]
x: 1  prin[prin[prin[prin[prin[prin[prin[x: x + 1]]]]]]]
print [1 2 prin [5 6]]
print [1 2 prin [5 6] 3]
print [1 print [2 print [3 3] 2] 1]
prin [1 prin [2 prin [3 3] 2] 1]
prin [1 prin [2 print [3 3] 2] 1]  
prin [1 print [2 prin [3 3] 2] 1]  
print [1 prin [2 prin [3 3] 2] 1]  
```
**CLI**
```
>> print [1 2 print [ 5 ]]
5
1 2
>> print [1 2 print 5 ]
5
1 2
>> print print 5
5
>> print [1 2 prin 5]
51 2
>> prin [1 2 print 5]
5
1 2
>> x: 1  prin[prin[prin[prin[prin[prin[prin[x: x + 1]]]]]]]
2
>> print [1 2 prin [5 6]]
5 61 2
>> print [1 2 prin [5 6] 3]
5 61 2  3
>> print [1 …
```
> FIX: issues #2047 (PRINT weirdness), #2393 (Recursive `print` issue)

- red.r
One less step to compile GUI Console by default for macOS
> gui-sys-call is only defined for Windows

- environment/console/GUI/core.red
- environment/console/help.red
Fixes #3472 
Tested on W7 (GUI+CLI) & Xubuntu (more test results are welcome)
Summary:
- `char-width` in gui console is changed to a float! for better arithmetic
- scrollbar is accounted for, albeit using a hardcoded 20 virtual pixels width
- `form-value` has no way to know at what column the value will be output (after 1 or 2 columns of text, or whether columns are of their minimum width or bigger, what separators were used) so I moved the ellipsizing code into `_print` which has a flag now that commands it to truncate the output
- basically every occurrence of `_print [... form-value ...]` became `_print/fit [... form-value ...]`
- improved `view` subsystem presence check (it wasn't working)
Yeah, I got pictures ☻
CLI:
GUI:
> FIX: issue #3472 (Help text sometimes overflows to the next line)

- environment/lexer.red
- tests/source/units/load-test.red
Fixes #2438
Issue arose from [symbol-rule](https://github.com/red/red/blob/c80ba51d8d1575a6b492c905d3d29570340073a8/lexer.r#L177) always succeeding without advancing the output. It relied on [tag-rule](https://github.com/red/red/blob/c80ba51d8d1575a6b492c905d3d29570340073a8/lexer.r#L517) to accept the input but the latter rejected it, and so it went on.
I did not extend or narrow lexical scope any rules, just added a check for input advancement. And tests.
```
>> load "a<=>"                          
*** Syntax Error: invalid value at "<=>"
*** Where: do                           
*** Stack: load                         
>> load "a</=>"                         
== [a </=>]                             
>> load "a<=/>"                         
== a<=/>                                
>> …
```
> Fix for #2438

- system/runtime/libc.reds
`fmod` function was maybe not needed in Red runtime, but as `libc` is used also for Red/System, could you please include it? Btw... there is more math related functions missing.. I can add them if you would accept it.
> FEAT: including fmod import in libc

- build/includes.r
- modules/view/backends/gtk3/comdlgs.reds
- modules/view/backends/gtk3/draw.reds
- modules/view/backends/gtk3/events.reds
- modules/view/backends/gtk3/font.reds
- modules/view/backends/gtk3/gtk.reds
- modules/view/backends/gtk3/gui.reds
- modules/view/backends/gtk3/handlers.reds
- modules/view/backends/gtk3/menu.reds
- modules/view/backends/gtk3/para.reds
- modules/view/backends/gtk3/text-box.reds
- runtime/collector.reds
- runtime/definitions.reds
- runtime/platform/image-gdk.reds
To merge more easily the development of the branch `rcqls/red:GTK-dev`, I simply pulled the `red/red:GTK` and copied the reds files of the `rcqls/red:GTK-dev`. As a consequence, I am loosing the git history (of the `rcqls/red:GTK-dev`) but in fact this is done on purpose since this history was not really interesting. Hope this PR could be a good starting point for people willing to contribute in the `red/red:GTK`.
Also in this PR, I intentionally remove the camera stuff that I will add soon when more complete. Some ugly DEBUG comments are still there but could be removed soon when the community would think that this stuff is more and more stable.
> A preliminary useable version of red/GTK

- .github/ISSUE_TEMPLATE/bug_report.md
Another possibility is to factor this section out into a dedicated message displayed on [this](https://github.com/red/red/issues/new/choose) page, but I don't know if Github supports such feature.
> FEAT: wordsmith 'Before submitting' section

- runtime/stack.reds
Fixes #1598, fixes #2538, fixes #3714, fixes #3866, fixes #3891 
Oh yeah... right... also: fixes #3733, fixes #3773, fixes #3831, fixes #3876 
Removes the crash from #1055, though does not solve it.
Tests will go into the PR #3781 instead
***
This https://github.com/red/red/blob/bf1706adb3df97052bd486c476f61a4221e3654d/runtime/stack.reds#L256-L265
or more particularly this https://github.com/red/red/blob/bf1706adb3df97052bd486c476f61a4221e3654d/runtime/stack.reds#L55-L63
invoked from L150 (error/reduce) here https://github.com/red/red/blob/bf1706adb3df97052bd486c476f61a4221e3654d/runtime/datatypes/error.reds#L141-L155
was destroying the stack - flattening it and filling with trash
If you look at the code of STACK_SET_FRAME, it's obvious it's doing something nasty. Even the assumption that …
> FIX: issues #1598, #2538, #3714, #3866, #3891

- environment/console/GUI/gui-console.red
- modules/view/backends/gtk3/gtk.reds
- modules/view/backends/gtk3/gui.reds
- modules/view/backends/gtk3/text-box.reds
- runtime/clipboard.reds
Add: read-clipboard and write-clipboard completed for Linux based on gtk_clipboard.
> Gtk: Fix input of gui-console for characters & and < by escaping them since rich-text is XML based

- environment/console/GUI/core.red
- environment/console/GUI/gui-console.red
- modules/view/backends/gtk3/comdlgs.reds
- modules/view/backends/gtk3/events.reds
- modules/view/backends/gtk3/gui.reds
hide-invisible inside do-events was not enough to deal with `visible?` facet. In gui-console opening about or settings weirdly makes tips visible again. This PR fix this issue.
> Gtk: fix visible? management

- modules/view/backends/gtk3/events.reds
- modules/view/backends/gtk3/gtk.reds
- modules/view/backends/gtk3/para.reds
- modules/view/backends/gtk3/text-box.reds
Escaping was made too early in the code. No more need to have a simplified escaping function so `g-markup-escape-text` is removed in favor of the original `g_markup_escape_text`. IMHO, the only problem that can occur is that styles only work when tags are embedded. This can be improved later...
> Gtk: fix issue with escaping on rich-text used by gui-console

- environment/console/GUI/gui-console.red
- modules/view/backends/gtk3/gtk.reds
- modules/view/backends/gtk3/gui.reds
`update-cfg font none` is called too early on Linux/GTK. This fixes the issue since called after `win/visible?: yes` which updates properly the font handler for the first time and required by `update-cfg font none` to update properly the caret at first.
> Gtk: Fix issue about bad caret position for gui-console when big font

- environment/reactivity.red
- tests/source/units/reactivity-test.red
Partial fix for #3333 - stops `is` from generating invalid reactions, by limiting `is` to words only and letting `react` deal with paths.
Includes tests for the fix + a little rewrite of reactivity tests, removing usage of common words like `a`, `b` etc., as these often cause problems with the compiler in code trying to reassign them later to a function or something.
> Issue 3333 fix

- environment/console/CLI/input.red
- environment/console/CLI/win32.reds
Fixes #3087, fixes #3678, together with PR #3884 fixes #3333 
1.red: `Red [] b: [1] ? b` (#3678)
2.red (#3333):
```
Red []
r: make reactor! [a: 1 b: is [a * 2] c: 0]
react/link func [x y][x/c: y/a * 3] [r r]
dump-reactions
```
3.red (#3087):
```
Red []
print system/console/size
ask "Press enter"
print system/console/size
```
Output:
```
>red --cli 1.red
B is a block! value.  length: 1  [1]
>red --cli 1.red | more
B is a block! value.  length: 1  [1]
>red --cli 2.red
1:---
Source: object [a b c]
Field: a
Action: [a * 2]
Target: b
2:---
Source: object [a b c]
Field: a
Action: func [x y][x/c: y/a * 3]
Args: [object [a: 1 b: 2 c: 3] object [a: 1 b: 2 c: 3]]
>red --cli 2.red | more
(same as previous)
>red --cli 3.red
213x48
Press enter
213x48
>red --cli 3.red | more
80x50
80x50
``` …
> FIX: issues #3087, #3678, part of #3333

- runtime/datatypes/string.reds
While studying the Red code, I found this place where both `either` branches produce absolutely the same result so this branching is not needed and removal of it simplifies the code.
> FIX: remove not needed 'either' branching

- environment/codecs/json/common.red
- environment/natives.red
Added docstring to `recycle`. Also fixed a very small typo in `translit` function.
> FIX: RECYCLE does not have a docstring #4033

- environment/console/GUI/core.red
- environment/functions.red
- environment/routines.red
- runtime/clipboard.reds
- runtime/platform/image-gdiplus.reds
- tests/source/units/all-tests.txt
- tests/source/units/clipboard-test.red
Also: Fixes #4055 
Allows to read/write from/to the clipboard:
**1. Images**
This is a bloody mess. See https://stackoverflow.com/a/6565158 , https://stackoverflow.com/a/46400011 , https://stackoverflow.com/a/15691001 for more info.
**TL;DR** Windows' clipboard only supports opaque images reliably. We can read/write alpha-enabled images in Red, but most programs will ignore the alpha. To avoid the troubles of GDI/GDI+/DIB/clipboard interaction, some programs also copy/paste raw image data into the clipboard (as PNG/JPEG/etc), so I made it to support this too: it writes the images in both PNG and DIB format, reads in any of PNG/JPG/GIF/DIB (in the order of preference).
`read-clipboard` in this case returns an `image!`
`write-clipboard` accepts an `image!`
`read-clipboard write-clipboard …
> FEAT: clipboard extension to support images and file lists, Windows only

- modules/view/backends/windows/base.reds
I believe `panel` face was not designed to display any "text" on it directly. It kinda worked using same code that does so for a `base`, but `base` with `color: none` does not paint it's background so it never did for the panel. Thus I disabled it. As a consequence the background is now painted by DefWindowProc even when it has a "text" facet assigned.
An alternative would be to redraw the panel manually using `base` code, but specifying a default window color, and *then* draw a text on it.
Let me know if I judged correctly.
> FIX: issue #3270 (Panel face with set text facet fills with black)

- environment/functions.red
- tests/source/units/replace-test.red
With this PR, Red's `replace` function becomes more compatible with R2 by supporting below forms:
```
replace "123" 1 "x" ; == "x23"
replace "abc" quote a: "x" ; == "xbc"
```
> FIX: #4079 replace on strings should work with non-formed arguments

- environment/console/GUI/core.red
You may disagree with #4156 but I'm going to use this anyway.
Fixes #4156 
Summary:
- `Shift+DEL` works as `Ctrl+X`
- `Ctrl+DEL` deletes until the end of the next word
- `Ctrl+Backspace` deletes until the start of the previous word
- `Ctrl+Left/Right` jump to previous word start / next word end
- path separators (among others) are considered word delimiters, so only one word in the path is deleted/skipped
> FIX: issue 4156 (Bugs in GUI Console keyboard shortcuts)

- tests/source/view/base-self-test.red
> TESTS: base-self-test: relaxed text size checks for W10 proofing

- system/formats/PE.r
Now Red Apps can use 4GB memory on 64-bit Windows system.
```
>> loop 240 [make block! 1024 * 1024]
== []
```
> On 64-bit editions of Windows, 32-bit applications marked with the IMAGE_FILE_LARGE_ADDRESS_AWARE flag have 4 GB of address space available.
https://docs.microsoft.com/zh-cn/windows/win32/memory/4-gigabyte-tuning
> FEAT: enable LARGE_ADDRESS_AWARE flag on Windows.

- system/utils/libRedRT-exports.r
These lines caused errors like this: `*** libRedRT Error: definition not found for red/OS-image/buffer-argb-to-abgr` during compilation with `-c -u` on GTK branch.
They probably will be needed back when merging GTK branch into master, see @qtxie comment in #4090.
> FIX: organize libRedRT exports for GTK branch

- runtime/clipboard.reds
Fixes #4284 
I can't explain why and how this works, but it does, at least on W7. With this "fix" I can't make `read-clipboard` or `write-clipboard` fail multiple times in a row anymore, and single failures are less frequent even if I'm aggressively using the clipboard.
> FIX: issue #4284 magic fix (Windows clipboard failure when accessed...)

- modules/view/backends/gtk3/events.reds
- modules/view/backends/gtk3/gtk.reds
- modules/view/backends/gtk3/gui.reds
- modules/view/backends/gtk3/handlers.reds
This PR fixes #4271, but only partially and in a two-fold manner, here's why:
1. Window decoration flags can be set separately with combination of [`gdk-window-set-decorations`](https://developer.gnome.org/gdk3/stable/gdk3-Windows.html#gdk-window-set-decorations) and [`GdkWMDecoration`](https://developer.gnome.org/gdk3/stable/gdk3-Windows.html#GdkWMDecoration) in `realize` signal handler (i.e. after allocation of low-level GDK resources), but it still leaves window at the mercy of a window manager, which is free to ignore all the (un)set bits when applying decorations; per documentation referenced above:
> Most window managers honor a decorations hint of 0 to disable all decorations, but very few honor all possible combinations of bits.
1. GTK itself offers only coarse-grained management …
> FIX: issue #4271 ([GTK] NO-BUTTONS window flag has no effect)

- modules/view/backends/windows/events.reds
Fixes #4280 by fetching DrawText flags via `get-para-flags` and applying them on text rendering. Not sure if regression tests are required though.
> FIX: issue #4280 ([View] custom font resets alignment for BUTTON, CHECK and RADIO)

- runtime/datatypes/integer.reds
- tests/source/units/convert-test.red
Fixes #4325. Also adds a couple of tests for `binary!` to `integer!` conversion.
>  FIX: issue #4325 (Runaway binary to integer conversion)

- runtime/datatypes/binary.reds
- runtime/datatypes/url.reds
- runtime/macros.reds
- tests/source/units/convert-test.red
Fixes #4272. Conversion from `any-list!` to `binary!` internally relied on `insert` action, which for `hash!` and `paren!` cases inadvertently overflowed the stack by converting (and pushing) the same value slot over and over again. So the issue was a byproduct of a more serious problem:
```red
>> insert #{} quote (1 2 3)
*** Internal Error: stack overflow
*** Where: insert
*** Stack:  
```
It also renames `ANY_LIST` macro so that it is consistent with other macro definitions in the same group. A couple of tests are provided.
>  FIX: issue #4272 (TO-BINARY with ANY-LIST argument behaves incorrectly except for BLOCKs)

- runtime/parse.reds
- tests/source/units/parse-test.red
Fixes #4318 by peeking a bit farther ahead during keyword processing and checking the presence of a sub-rule.
>  FIX: issue #4318 ([Parse] SET and COPY work even without a sub-rule)

- runtime/datatypes/object.reds
Fixes #4364 by taking `flat?` flag into account when indenting content of a serialized buffer.
> FIX: issue #4364 (Extra indentation spaces in `mold/flat` output)

- runtime/datatypes/image.reds
- tests/source/units/regression-test-red.red
Closes #4056 and provides relevant regression tests.
> FIX: issue #4056 ([Regression] `tail?` and `empty?` on image are missing by one pixel)

- environment/functions.red
- tests/source/environment/functions-test.red
This PR adds missing `copy` to `split` function to fix below bug:
```
>> a: split "a," ","
== ["a" ""]
>> b: split "b," ","
== ["b" ""]
>> same? a/2 b/2
== true
```
> FIX: missing copy in split function

- runtime/natives.reds
- tests/source/units/serialization-test.red
Fixes #4383 by throwing an error on non-positive `size` argument. FYI, Rebol3 does almost the same:
```red
>> to-hex/size 123 1
== #B
>> to-hex/size 123 0
== #???
>> to-hex/size 123 -1
** Script error: invalid argument: -1
** Where: to-hex
** Near: to-hex/size 123 -1
```
> FIX: issue #4383 (to-hex is not doing proper bounds check for its `/size` value).

- environment/actions.red
- runtime/datatypes/tuple.reds
Fulfills and closes #1956. `complement` on `tuple!` values is now allowed and matches Rebol behavior:
```red
>> complement 254.252.252.248
== 1.3.3.7
```
I didn't find any `tuple!`-specific test suite and don't know where else to put them (if that's needed at all).
> FEAT: grant wish #1956 (complement should be allowed on tuples)

- modules/view/backends/windows/events.reds
The default alignment (horizontally/vertically centered) is now applied if there are no para settings. Closes #4280.
> FIX: extra fix for issue #4280.

- modules/view/VID.red
- modules/view/backends/gtk3/events.reds
- modules/view/backends/gtk3/gtk.reds
- modules/view/backends/gtk3/gui.reds
- modules/view/backends/gtk3/handlers.reds
- modules/view/backends/platform.red
This PR is a follow-up to https://github.com/red/red/pull/4255. It fixes #4244, closes #4245, and implements 3-state mode for `check` face (described [here](https://github.com/red/docs/pull/211)).
I gotta say adding 3-state checkbox was a huge hassle due to various GTK quirks, the major one being a complete absence of 3-state style for `GtkCheckButton`, so I had to emulate it with ingenious workarounds. It bulked out the GTK backend codebase but faithfully mimics behavior on other platforms.
> FIX: [GTK] issues #4244 and #4245

- modules/view/backends/macOS/classes.reds
- modules/view/backends/macOS/delegates.reds
- modules/view/backends/macOS/gui.reds
- modules/view/styles.red
Simplifies interface and Obj-C type signature of calendar's delegate on macOS, also groups calendar with other list-like styles that offer a selection of a single value.
> FEAT: slight refactoring

- runtime/natives.reds
`foreach <word> <non-empty map> <block>` now reports an invalid argument:
```red
>> foreach value #(a b)[]
*** Script Error: invalid argument: value
*** Where: foreach
*** Stack:  
>> foreach value #()[]
```
Note that the last example is pertinent to _all_ cases with an empty `series` argument, regardless of its type:
```red
foreach [whatever #really /I don't/care][][]
```
This PR closes #3910. I'm not completely satisfied with the change though, as it makes `while [foreach-next][...]` loop less tight than it should be. An alternative solution is to move check into second `either` branch in `foreach*` before the loop kicks in.
Related tickets: https://github.com/red/red/issues/2279, https://github.com/red/red/issues/617, https://github.com/red/REP/issues/58.
> FIX: issue #3910 (Wrong error message when using foreach wrongly on map)

- runtime/natives.reds
- system/runtime/libc.reds
From now on it's properly named as `log-e`. `log-b` compiler intrinsic can be used to take base-2 logarithm of integer values.
> FIX: typo in C-lib natural logarithm import

- environment/actions.red
- runtime/datatypes/block.reds
- runtime/datatypes/string.reds
- tests/source/units/series-test.red
SORT-related. Fixes #3583 
Summary:
- support of `/skip i`, `/skip/all i` and `/skip/compare i j` for `binary!`, `vector!`, `any-string!`
- empty `/part` is allowed with any `/skip` to do nothing (it raised an error previously)
- `/all/compare int` is an erroneous combination now
- `/compare int` without `/skip` is an error
- `/all` without `/skip` is an error
It is currently somewhat forgiving about bad refinement combos when given an empty input (not my doing), but it's an optimization worth having.
> FIX: issue #3583 and some

- runtime/datatypes/function.reds
- tests/source/units/function-test.red
Resolves #3595. Docstring after `return:` spec is now allowed, but only if it is located at the tail of the function spec (see newly added tests for examples).
> FIX: issue #3595 (`return:` for func now chokes if it has a doc string (interpreter))

- environment/codecs/csv.red
- tests/source/units/csv-test.red
When fixing #4424 I found other problem. So here's a fix for that one.
> FIX: TO-CSV can encode block of maps/object properly

- environment/system.red
- runtime/datatypes/money.reds
Adds `money!` accessors to `system/catalog/accessors` and rewrites main division loop, thus avoiding a bug with subroutines that I mentioned at some point.
> FEAT: minor additions to MONEY! datatype.

- modules/view/draw.red
Fulfills and closes #3055. It does not cover [deprecated API](https://doc.red-lang.org/en/draw.html#_deprecated_api) though, and I don't think it should.
Relevant tests can be provided, but really, `percent!` and `float!` are one and the same, so there shouldn't be any problem with that.
> FEAT: grant wish #3055 (DRAW supports PERCENT! for SCALE)

- runtime/datatypes/series.reds
- runtime/lexer.reds
Marks values in lexer's buffer.
> FIX: issue #4433 ([CRASH] when loading a big map)

- runtime/datatypes/block.reds
- runtime/datatypes/money.reds
- tests/source/units/money-test.red
**TL;DR:** `=`, `<>` and `=?` always return `logic!` and differ only in the level of strictness. `<`, `<=`, `>`, `>=` error out if two different currencies are compared. `find` permits a level of flexibility by dispatching on presence/absence of currency code.
https://github.com/red/docs/pull/227
---
The previous design sketch of `money!` comparison aimed to minimize user mistakes when dealing with monetary amounts and financial calculations, all at the cost of being more ornery: comparison between two `money!` values of different currencies always resulted in an error, regardless of the comparison type.
This hinged on the idea that what is compared are not the Red values, but real-world monetary values that they denote: that is, the question of (in)equality of two currencies is …
> FEAT: update MONEY! comparison semantics.

- .travis.yml
Travis-CI will terminate a running script that doesn't output anything in 10 minutes and won't execute any `after_..` phases. In our case, it won't update the status badges.
Adding `travis_wait 30` before a command, will give it more time to execute (30 minutes) AND if the command take longer than that, it will be terminated BUT `after_..` phases will be executed.
> FEAT: improve Travis-CI notification on failure

- runtime/datatypes/binary.reds
- runtime/datatypes/block.reds
- runtime/datatypes/map.reds
- runtime/datatypes/object.reds
- runtime/datatypes/string.reds
- runtime/hashtable.reds
- runtime/macros.reds
- runtime/natives.reds
- runtime/parse.reds
- runtime/redbin.reds
This PR is informed mostly by `ref!`-related bugs and issues that come up time and again: it was implemented with an assumption that runtime relies on `TYPE_ANY_STRING` and `ANY_STRING?` macros. As can be seen in the applied changes, this did not hold in the majority of cases.
I also took the liberty to simplify `ANY_SERIES?` macro, remove dead `CHECK_COMPARE_OTHER` definition that wasn't used in the codebase, and refactor conditions that use `ANY_WORD?`.
Among the way the following inconsistency was fixed:
```red
>> head change "" <a>
== "a"
>> head insert "" <a>
== "<a>"
```
Now both actions preserve angle brackets of `tag!` values, the same way Rebol does.
> FIX: refactor conditional usages of typeset macros.

- modules/view/backends/windows/gui.reds
This line is leaking memory on W7 in the branch https://github.com/red/red/pull/4300 where images are garbage collected
https://github.com/red/red/blob/master/modules/view/backends/windows/gui.reds#L2644
It comes from [this commit](https://github.com/red/red/commit/32c7f24c114919bdfc6bc3ebb442d941ce167ddf) which is quite old. I can't tell at a glance if Draw can delete this DC during WM_PAINT (what a mess!), but:
- draw only gets called for non-layered `base` (and I guess `rich-text`) face: see [here](https://github.com/red/red/blob/48eb6f749d731806fe7322a7bf2af160de718ecc/modules/view/backends/windows/base.reds#L487). Even then it's totally unclear if *all* branches will delete it. Even if they do, I suggest we decisively get rid of such non-locality as a primary source of bugs.
- W7 …
> FIX: leaking OS handle eats memory when converting face to image

- tests/source/units/float-test.red
Tests for expected:
```
>> to float! "12e"
*** Script Error: cannot MAKE/TO float from: 12e
*** Where: to
*** Stack:
```
(Throws error rather than crashes)
> TESTS: float-test.red - issue #4250

- tests/source/units/lexer-test.red
- tests/source/units/regression-test-red.red
Expected:
```
>> [$non]
*** Syntax Error: (line 1) invalid money at $non]
*** Where: case
*** Stack: load 
```
(As opposed to a less readable error)
> TESTS: regression-test-red.red - issue #4119

- run-all.r
Using this command:
```
rebol -qs run-all.r --binary <path-to-compiler>
```
for running the quick-test framework resulted in this error:
```
** Script Error: bin-complier has no value
** Near: if any [
bin-compiler = "--batch" 
bin-complier = "--each"
] [
bin-compiler: none
]
```
on account of a small typo.
> FIX: quick-test typo in code handling --binary

- environment/networking.red
This PR fixes below issue:
```
>> u1: encode-url decode-url http://a.com/
== http://a.com/
>> u2: encode-url decode-url ftp://b.com/
== ftp://b.com/
>> u1
== ftp://b.com/
```
I also use `make url! 60`, with a rough idea of average URL size.
I could only find a ten years old research on this:
http://www.supermind.org/blog/559/average-length-of-a-url
http://www.supermind.org/blog/740/average-length-of-a-url-part-2
> FIX: encode-url copy problem

- runtime/datatypes/error.reds
- tests/source/units/regression-test-red.red
Fixes #4627 and provides a regression test. The issue was caused by a commit fdf7a3a introduced during the work on the new lexer. It slightly changed error processing to make syntax errors more readable:
https://github.com/red/red/blob/151e6088efec77cf87ed024e7fb5660f55fa3a0b/runtime/datatypes/error.reds#L149
That is, reported values are now `form`ed rather than `mold`ed. This makes sense, because with `mold` syntax errors would look like this:
```red
>> ]
*** Syntax Error: "(line 1)" missing #"[" at "]"
*** Where: transcode
*** Stack: load 
```
OTOH, once values are `form`ed, the other types of error messages become pretty obscure and uninformative:
```red
>> 1 < [2]
*** Script Error: cannot compare 1 with 2 ; Of course you can Red, believe in yourself!
*** Where: <
*** Stack: 
>> null > …
```
> FIX: issue #4627 (reported values in error messages are not properly displayed).

- compiler.r
- tests/source/compiler/regression-test-redc-5.r
Fixes #4526 and provides a regression test for a compiler.
The issue was caused by one of the internal functions using `exit` and returning `unset`. I surmise this short-circuit path should rather yield a logical false.
> FIX: issue #4526 ([Compiler] Internal error `defer needs a value`). 

- lexer.r
- system/tests/source/compiler/regression-test-rsc.r
- tests/source/compiler/regression-test-redc-5.r
- tests/source/units/regression-test-red.red
Resolves #2671 for Red and Red/System compilers. Relevant regression tests are provided.
There are at least 3 different issues coalesced in here:
1. `%lexer.r` accepted only escaped `^(...)` characters with 2-6 digits;
1. If an escaped character was malformed, `%lexer.r` treated it as a non-escaped sequence of characters; e.g. `"^(foo)"` turned into `"(foo)"`, `"^(0)"` into `"(0)"`;
1. Red/System `byte!` literals were malformed if the number of their digits was not evenly divisible by 2 (same issue with `enbase` as in https://github.com/red/red/pull/4621).
> FIX: issue #2671 (Char in numeric form is not supported for values from 0 to 9).

- runtime/datatypes/string.reds
- tests/source/units/series-test.red
Fixes #4204 and extends `series!` test suite.
With `find/last` the search happens backward, from end to start, but in case of `last` combined with `part` the upper limit was incorrectly calculated: it always happened from the series end rather than from the boundary delineated by `/part` argument.
What's more important is that the other limit wasn't correctly calculated either:
https://github.com/red/red/blob/20aded310d83709cb22294a4861c313495c80333/runtime/datatypes/string.reds#L1908-L1912
Note the `buffer - limit` part. This means that the lower boundary resides outside the series buffer, somewhere in `series!` meta info or even before it. Knowing that this meta info is 20 bytes in width and likely contains `01` byte in the header (a bit flag that specifies that series is used), we can, …
> FIX: issue #4204 (FIND/LAST does not honor /PART). 

- runtime/parse.reds
- tests/source/units/parse-test.red
Fixes #4591 by extending the relevant conditional check in `ST_DO_ACTION` branch: prior to the fix it countered only the `0 <rule>` case by jumping over the sub-rule.† Tests are provided.
An interesting realization coming from this PR is that `0` can act as an ad-hoc comment construct in Parse rules, sort of:
```red
comment: 0
parse "Ratsnake" [to end comment "four claps - You did it!"]
```
† Which should be a single value (see #3679).
>  FIX: issue #4591 (PARSE 0 0 <value> matches one value).

- runtime/datatypes/ref.reds
Because of a missing `modify` action, `ref!`s owner could not be changed.
```red
>> reactor [foo: @bar]
*** Script Error: modify does not allow ref for its target argument
*** Where: modify
*** Stack: reactor
```
This is fixed by inheriting this action from `string!`, which allows usage of `ref!` in reactive code.
```red
>> r: deep-reactor [foo: @bar qux: is [last foo]]
== make object! [
foo: @bar
qux: #"r"
]
>> append r/foo "bara"
== @barbara
>> r/qux
== #"a"
```
> FIX: REF! cannot be used in ownership system.

- README.md
- build/includes.r
- environment/codecs/BMP.red
- environment/codecs/GIF.red
- environment/codecs/JPEG.red
- environment/codecs/PNG.red
- environment/console/CLI/POSIX.reds
- environment/console/GUI/old/terminal.reds
- runtime/crypto.reds
- runtime/datatypes/common.reds
- runtime/definitions.reds
- runtime/platform/netbsd.reds
- runtime/red.reds
- runtime/simple-io.reds
- runtime/threads.reds
- runtime/utils.reds
- system/compiler.r
- system/config.r
- system/formats/ELF.r
- system/runtime/POSIX-signals.reds
- system/runtime/common.reds
- system/runtime/lib-names.reds
- system/runtime/netbsd.reds
- system/runtime/start.reds
- system/targets/IA-32.r
- usage.txt
Successfully ported Red to NetBSD (x86, non-GUI console), fixing some FreeBSD and ELF generation issues along.
Everything seems to work so far, but you need NetBSD/i386 to run it, as NetBSD/amd64 lacks 32-bit libcurl in binary packages. You could probably build 32-bit libcurl manually and place it properly for multiarch setup (NetBSD supports this in general), but this is distro-specific effort and not related to the porting part itself.
(Separate commits squashed to avoid merge issues)
> FEAT: Add NetBSD Target

- modules/view/draw.red
This feature is GDI+ specific, rarely used and not easy to be implemented on other platforms.
> FEAT: remove `matrix-order` command in DRAW.

- modules/view/backends/gtk3/gui.reds
example 1:
```
d: ["1" "2" "3" "4" "yikes!"]
view [tl: text-list 100x300 data d [print 1] button "xxx" [either tl/selected [tl/selected: tl/selected + 1][tl/selected: 1]]]
```
example 2:
```
d: ["1" "2" "3" "4" "yikes!"]
view [tl: text-list 100x300 data d [print 1] button "xxx" [append d "x"]]
```
> FIX: when change selected/data of text-list, shouldn't trigger on-changed

- runtime/parse.reds
- tests/source/units/parse-test.red
Fixes #4153 by rewriting the logic of `insert` rule from scratch and provides relevant tests. Parse documentation is also updated: https://github.com/red/docs/pull/241. Also partially fixes #4101 as a follow-up to https://github.com/red/red/pull/4620.
As it turns out, `insert` supported a positional mode (like `remove` and `change`) where it can insert value at previously marked position instead of the current one. This mode was never properly implemented, however, and there were several oversights inside `insert`'s logic: both of these factors contributed to the reported issue.
Here, for example, `insert` scans the value in rule block to check if it's an input position: and if it is, then `cmd` pointer is properly updated.
https://github.com/red/red/blob/e01760493eaac0c1f5dee7cb8e9149b859 …
> FIX: issue #4153 ([Parse] odd behavior of INSERT).

- environment/functions.red
- tests/source/environment/functions-test.red
This complete rewrite of `math` dialect fixes #2532 and, hopefully, addresses the modest goal of evaluating given expression using PEMDAS precedence rules.
```red
>> math [1 + 2 * 3]
== 7
>> math [(1 + 2) * 3]
== 9
>> math [10 + 10 ** 2 ** 3]
== 100000010
>> math [10 + 10 % 2]
== 10
>> math [8 / 5 % 2]
== 1
```
Covering all edge-cases (like e.g. what `quote * 1` should do, or what if `/` isn't really bound to division `op!`, what if there's more than one right-associative operator of the same precedence level) is beyond the scope of this endeavor. `math`, as I see it, is intended to be a [stele](https://en.wikipedia.org/wiki/Stele) that engraves tricks of Parse trade and shows how one can make a dialect.
At least [Picosheet demo](https://github.com/red/code/blob/master/Showcase/picosheet.r …
> FIX: issue #2532 (Math doesn't follow the arithmetic precedence for %, **)

- runtime/datatypes/native.reds
This PR fulfills and closes https://github.com/red/REP/issues/51 by implementing `body` reflector for `action!` and `native!` values.
```red
>> load rejoin [body-of :now reflect :negate 'body]
== 9214
```
Rationale and use-cases for this are described in https://github.com/red/red/issues/3359#issuecomment-523405544.
> FEAT: grant wish red/REP#51 (BODY-OF on ACTION! and NATIVE! values)

- environment/functions.red
- tests/source/units/replace-test.red
Closes #4174, provides regression tests, and replaces `replace` (no pun intended) by rewriting it from scratch in a more modular fashion. The existing semantics is hopefully preserved, but, looking at how complicated its internal dispatching logic is, I think a couple more tests might be in order.
> FIX: issue #4174 (`replace/all/deep` hangs up).

- environment/actions.red
- runtime/actions.reds
- runtime/datatypes/pair.reds
- runtime/datatypes/port.reds
- runtime/datatypes/series.reds
- runtime/datatypes/tuple.reds
- tests/source/units/all-tests.txt
- tests/source/units/series-test.red
- tests/source/units/tuple-test.red
- utils/redbin.r
Fulfills and closes #3004 (also closes https://github.com/red/REP/issues/28) by implementing `reverse/skip` for `series!` and `tuple!`. `port!` and `pair!` actions were modified to support an extra argument, but currently ignore it: `port!` because it's TBD, and `pair!` because it doesn't make much sense and it ignores all the refinements anyway.
`series!` tests were updated to cover this new feature; for `tuple!` I created a dedicated test suite.
Implementation follows `find/skip` semantics as a reasonable default, that is:
- `size` should be positive `integer!`;
- `size` should be less than or equal to `length` (either length of the `series!` or length specified by `/part`);
- `length` should be evenly divisible by `size`.
The basic logic of the algorithm (rotation by swapping) remains …
> FEAT: grant wish #3004 (/SKIP refinement for REVERSE).

- compiler.r
- tests/source/units/regression-test-red.red
Fixes #734 and provides a regression test. Regression itself occurred 7 years ago after refactoring of `emit-push-word` in https://github.com/red/red/commit/2b1ec3072f35f8690f4142845c7321ef98f12b50.
https://github.com/red/red/blob/02776dcf50c085b3fe9c207df88bdaceb8c5b3c0/compiler.r#L408
Innocently-looking line coupled with Rebol2 shenanigans is surely a recipe for disaster:
```rebol
>> rebol/version
== 2.7.8.3.1
>> foo: quote 'bar
== 'bar
>> reduce [:foo foo]
== ['bar bar]
```
So, in the line above, even though `name` is set to `lit-word!`, fetching it without using `get-word!` decays said `lit-word!` to `word!`, which in turn leads to an incorrectly inferred type.
> FIX: issue #734 (lit-word variables decay to word when evaluated).

- runtime/datatypes/float.reds
- tests/source/units/float-test.red
Fixes #4574 by implementing the QNaN behavior proposed in the ticket. `float!` test suite is extended to cover the relevant `x % y` cases.
The fix covers only operations between `number!` values that can be casted to `float!`, things like ↓ are still there (and should stay there IMO, as the behavior is very datatype-specific):
```red
>> 1.2.3 % 0.0
== 0.0.0
>> 1x2 % 0.0
*** Math Error: attempt to divide by zero
*** Where: %
*** Stack:  
>> 0:0 % 0.0
== --2147483648:-2147483648:00 ; #3418 ?
```
> FIX: issue #4574 (Remainder raises errors where should return a NaN).

- modules/view/VID.red
- modules/view/view.red
Fixes #4321 by removing shared state from VID context that `layout` is supposed to modify.
> FIX: #4321 (Shared state in LAYOUT causes stack overflows)

- runtime/allocator.reds
Corrected bit layout in series flags - previously there was 1 bit of an overlap between `<reserved>` and `unit`.
> FIX: minor bit layout correction

- runtime/interpreter.reds
- tests/source/units/evaluation-test.red
- tests/source/units/regression-test-red.red
also provides tests to ensure `do` cannot be used to make variadic calls
> FIX: regression in PR 4144

- runtime/datatypes/binary.reds
- tests/source/units/serialization-test.red
Fixes #4365 and provides serialization tests for `binary!` that cover `mold/flat` case.
> FIX: issue #4365 (`mold/flat` has no effect on binary values).

- compiler.r
- runtime/datatypes/object.reds
- system/utils/libRedRT-exports.r
- tests/source/compiler/regression-test-redc-1.r
- tests/source/compiler/regression-test-redc-2.r
- tests/source/compiler/regression-test-redc-3.r
- tests/source/compiler/regression-test-redc-4.r
- tests/source/compiler/regression-test-redc-5.r
With tests.
Make compiler generate `object/loc-ctx-fire-on-set* ctx||459 exec/~parent` instead of `object/fire-on-set* ~self exec/~parent`
> [view] handle firing on-set functions properly when using self inside objec's method

- runtime/natives.reds
For the sake of consistency with Rebol's behavior and the recent change in `get` https://github.com/red/red/commit/3fc8ef25b7328d8ddeff362761d0a21798047c82, `value?` now checks value referenced by `any-word!`, not just `word!`.
> FEAT: VALUE? native supports ANY-WORD! argument

- compiler.r
- tests/source/compiler/regression-test-redc-5.r
Provides compiler regression test for #4613, also fixes a minor omission: currency symbols from the header are now uppercased and processed in "normalized" form.
> TESTS: regression test for issue #4613 (compiled script crashes on MONEY! literal with user-defined currency code).

- runtime/datatypes/object.reds
- tests/source/units/object-test.red
`changed` property was added to objects in 05f99635 and is briefly described [here](https://github.com/red/red/wiki/%5BNOTE%5D-Undocumented-features#changed-reflector-in-objects). It works as intended with an exception of bulk `set` changes (i.e. `set <object> ...`) — this PR fixes that ommission, along with some minor out-of-range bug within `object/set-many`.
Relevant tests are also provided.
> FIX: bulk SET changes are ignored by CHANGED reflector.

- usage.txt
Synching options list with the readme file. Would be better for `usage.txt` to be transcluded into it somehow.
> FEAT: mention --NO-VIEW flag in toolchain options.

- environment/codecs/JSON.red
- tests/source/units/json-test.red
before/after
```
length: 1000000
698 ms  [save/as bin: #{} s1 'json]
5297 ms [s2: load/as bin 'json]
s2 == s1 : false
```
```
length: 1000000
548 ms  [save/as bin: #{} s1 'json]
267 ms  [s2: load/as bin 'json]
s2 == s1 : true
```
> 20x faster JSON string decoder

- runtime/datatypes/string.reds
- tests/source/units/json-test.red
See crash reports from [January 20, 2021 1:10 AM](https://gitter.im/red/codecs?at=600758c9d8bdab473947fe66)
Cause: `string/overwrite-char` extended the series where it wasn't needed or expected.
> FIX: removed uncalled-for series expansion

- runtime/redbin.reds
- tests/source/units/redbin-codec-test.red
Waiting for @9214 review ;)
Summary:
- Fixes #4803 by dynamically adjusting buffers size
- Reduces load time from O(n^2) to O(n) by using hashtable
Before the PR:
```
testing with 5000 strings..
*** Internal Error: internal limit reached: 20000
*** Where: encode
*** Stack: clock save
```
Dynamic but without hashtable:
```
testing with 5000 strings..
60.0 ms	[save/as clear bin b 'redbin]
2.00 ms	[c: load/as bin 'redbin]
loaded data valid? =  true
testing with 10000 strings..
219 ms	[save/as clear bin b 'redbin]
0.0 μs	[c: load/as bin 'redbin]
loaded data valid? =  true
testing with 15000 strings..
475 ms	[save/as clear bin b 'redbin]
3.00 ms	[c: load/as bin 'redbin]
loaded data valid? =  true
testing with 20000 strings..
829 ms	[save/as clear bin b 'redbin]
985 μs	[c: load/as bin 'redbin] …
```
> FIX: issue #4803 (Redbin a little too tight?)

- modules/view/utils.red
Why not? I haven't found a single use of `distance?` in Red codebase. But found myself reinventing the pair distance a few times already.
```
>> distance? object [offset: 0x0 size: 0x0] object [offset: 0x0 size: 1x1]
== 0.7071067811865476
>> distance? 0x0 1x1
== 1.414213562373095
```
An alternative would be to define `(length? A - B) -> float!`.
> FEAT: define distance? for pairs

- environment/actions.red
- runtime/datatypes/float.reds
- runtime/datatypes/integer.reds
- runtime/datatypes/money.reds
- tests/source/units/float-test.red
- tests/source/units/integer-test.red
- tests/source/units/money-test.red
- tests/source/units/pair-test.red
- tests/source/units/time-test.red
Following the discussion :point_up: [April 22, 2021 9:27 PM](https://gitter.im/red/help?at=6081c02db6a4714a29ded202) and TG chat.
**Summary**
Rationale: to not create special cases where they aren't required
Example:
```
>> round/to pi 1
== 3
>> round/to pi 1e-10
== 3.1415926536
>> round/to pi 1e-100
== 3.141592653589793
>> round/to pi 1e-500
*** Math Error: math or number overflow
>> round/to pi 0
*** Math Error: math or number overflow
```
As `scale` approaches zero we should expect the result to come closer and closer to the original value.
With the `lim (round/to value scale) = value` when `scale -> 0`.
The zero can be reached in practice as mentioned in the above discussion, so it makes sense to handle it automatically, leaving programmer with less headaches.
This PR implements `x = …
> FEAT: transparent round/to x 0

- runtime/natives.reds
error/capture may trigger GC. free-virtual will check system/thrown.
In this case, `system/thrown` is RED_THROWN_ERROR when free-virtual is called.
> FIX: reset system/thrown before capturing call stack in error!.

- runtime/datatypes/float.reds
- tests/source/units/regression-test-red.red
Fixes #4900 by following GCC semantics for x % infinity.
Also removes dead code.
> FIX: 4900 (fmod platform discrepancy leads to modulo ambiguity)

- runtime/natives.reds
- tests/source/units/float-test.red
Fixes #2244, fixes #3441 
Let @dockimbel approve the changes.
Should be merged AFTER the PR https://github.com/red/red/pull/3902/ or some tests will fail
Summary:
- `tangent 90.0` yields +infinity
- `tangent -90.0` yields -infinity
- `tangent ±1.#inf` yields NaN
- `arctangent 1.#inf` yields 90.0
- `arctangent -1.#inf` yields -90.0
- `arcsine x` for `x < -1 or x > 1` yields NaN
- `arcsine 1.#nan` yields NaN
- `arccosine x` for `x < -1 or x > 1` yields NaN
- `arccosine 1.#nan` yields NaN
- tests to cover this behavior as well as previously working but untracked cases
> FIX: issues #2244 and #3441

- environment/actions.red
- runtime/datatypes/block.reds
- tests/source/units/find-test.red
- tests/source/units/switch-test.red
Fixes #4911
Adds tests for #2125
Removes some `switch` kludges made obsolete by commit https://github.com/red/red/commit/32d353efea0fcb53660db88a702a92b315a5168b
`find [#[integer!] 1] integer!` now matches `1` only, not the datatype (for less surprises and consistency with typesets)
`find/only` also enables the use of hash lookups for datatypes and typesets
> FIX: Issue 4911 (FIND type! vs FIND typeset! inconsistency)

- runtime/natives.reds
In Ubuntu Linux and RPi `atan2 inf inf` returns `pi / 4`, whereas in msvcrt it returns `nan`. I consider `nan` to be a valid result here, same as `inf / inf` is `nan`, not `1.0`.
This PR patches `arctangent2` native to return `1.#nan` and be consistent for this special case.
Failing `float-arctangent2-5` test should start passing.
> FIX: workaround for libc atan2 bug

- runtime/natives.reds
- runtime/unicode.reds
- tests/source/units/lexer-test.red
Fixes #5000 by skipping BOM in `transcode*` native.
Also noticed extra sized cache allocation, reduced following the logic of https://github.com/red/red/pull/4995
> FIX: issue #5000 (CRASH when molding UTF8 string loaded from binary)

- environment/system.red
didn't do any polishing, just added the type of `type`:
```
>> transcode-trace "1 + 2;"
prescan integer!(datatype) 1x2 1 " + 2;"
scan integer!(datatype) 1x2 1 " + 2;"
load integer!(datatype) 1 1 " + 2;"
prescan word!(datatype) 3x4 1 " 2;"
scan word!(datatype) 3x4 1 " 2;"
load word!(datatype) + 1 " 2;"
prescan integer!(datatype) 5x6 1 ";"
scan integer!(datatype) 5x6 1 ";"
load integer!(datatype) 2 1 ";"
prescan comment(word) 6x7 1 ";"
scan comment(word) 6x7 1 ""
== [1 + 2]
```
> FEAT: output mode details in transcode-trace

- environment/natives.red
Seems like it had been copy+pasted from `new-line`. Updated the docs and return type
> FIX: Change spec for `new-line?` native

- environment/functions.red
benchmark source:
```
Red [] 
do %../common/clock.red
empty1: func [
{Returns true if a series is at its tail or a map! is empty} 
series [series! none! map!] 
return: [logic!]
][
case [
series? series [tail? series] 
map? series [series = #()] 
none? series [true]
]
]
empty2: func [
{Returns true if a series is at its tail or a map! is empty} 
series [series! none! map!] 
return: [logic!]
][
either series [zero? length? series][true]
]
do [loop 5 [
clock/times [empty1 none   ] 1000000
clock/times [empty1 []     ] 1000000
clock/times [empty1 [a b]  ] 1000000
clock/times [empty1 #()    ] 1000000
clock/times [empty1 #(a: b)] 1000000
print ""
clock/times [empty2 none   ] 1000000
clock/times [empty2 []     ] 1000000
clock/times [empty2 [a b]  ] 1000000
clock/times [empty2 #()    ] 1000000 …
```
> FEAT: faster/simpler empty? function

- modules/view/backends/windows/events.reds
The text alignment for `toggle` objects is ignored/reset when its `para` is configured.
Short example:
```red
view [ button 25 bold "A" toggle 25 bold "B" ]
```
Output:
> FIX: para breaks `toggle` alignment

- .github/workflows/RPi.yml
Rebol 2.7.8 is freezing on Windows when building the RPi tests.
> CI: build RPi/ARM tests on Linux host.

- runtime/stack.reds
```
args-series = series-buffer! + payload + padding
```
`args-series/size` is the `payload` size.
`args-series/offset` is the start of the `payload`.
So `a-end` should be
```
a-end: as cell! (as byte-ptr! args-series/offset)  + args-series/size
```
> FIX: stack/a-end and stack/c-end are not 16 bytes aligned

- environment/functions.red
Chat with Gregg reminded me that /delta was added before we had `dt`, so there's no point in it other than to confuse people.
> FEAT: removed /delta from clock

- modules/view/backends/windows/events.reds
Most wheel offset values seem to be not exceeding 1500, so 24000 seems like a reasonable limit that should not cause problems.
> FIX: workaround for #5110

- modules/view/RTD.red
view [rich-text data [font 9  i "" /i /font]]
> FIX: cannot use empty string in RTD

- README.md
Note updated to use PowerShell instead of CMD to prevent `PROGRAM ERROR: Invalid encapsulated data` error.
> Added info about Invalid encapsulated data error

- modules/view/view.red
EVT_SELECT changes the /text facet in place in get-text function. https://github.com/red/red/blob/master/modules/view/backends/windows/events.reds#L568
> FIX: issue #5297 (Drop-down data being corrupted after 'selected set)

- tests/source/compiler/preprocessor-test.r
- utils/preprocessor.r
Fixed the tests, but I'm lazy to add preprocessor support for this new feature:
```
>> quote 2 * 3
== 6
```
Hopefully we'll get rid of R2 dependency sooner or later.
> FIX: preprocessor/fetch-next updates

- environment/console/CLI/wcwidth.reds
In Red/System header, File: has wrong name: %win32.reds
> FIX: edit Red/System header, File: %wcwidth.reds

- modules/view/backends/gtk3/handlers.reds
While using base component with transparency, the GTK backend checks for transparent pixel and triggers events when necessary. This fix is related to the calculation of the position of these pixels, avoiding negative values when mouse Y is 0.
This fix is related to a previous one: [4743](https://github.com/red/red/issues/4743)
@qtxie maybe you had some specific use case in mind. Could you check this one, please?
Thanks in advance.
> FIX: access violation on mouse events in GTK backend

- environment/functions.red
In current `average` function there is `to float!` conversion which is not necessary anymore because `divide` returns float now.
```red
average: func [
"Returns the average of all values in a block"
block [block! vector! paren! hash!]
][
if empty? block [return none]
divide sum block to float! length? block
]
```
Note that this change also makes `average` returns integer in some cases, but this could be a good change:
```red
>> average [0]
== 0
>> average [1 2 3]
== 2
```
> No need "to float!" in average

- docs/red-system/red-system-specs.txt
- system/emitter.r
- system/formats/Mach-O.r
- system/formats/PE.r
Fix typos in the comment section of system and docs
> FIX: 4 typos in system and docs

- runtime/natives.reds
Bug was due to incomplete copy/paste change and dupe Point2D! case. Point3D! type is _intentionally_ used for both cases, reusing `pt` var.
> FIX: Point3D! always returns false from `zero?`
